export const ENGINE_CONTRACTS = [
  {
    id: "projectIdentity",
    phase: "identity",
    priority: 10,
    module: "./engines/projectIdentityEngine.js",
    exportName: "analyzeProjectIdentityBatch",
    dependsOn: [],
    inputContract: {
      requiredAny: [["address", "pairAddress", "symbol", "name"]],
      optional: ["chain", "url", "website", "twitterHandle", "githubRepo"],
    },
    outputContract: {
      requiredAny: [["projectIdentityVerdict", "identityResolutionScore", "projectIdentity"]],
      scoreFields: ["identityResolutionScore", "identityRiskScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "sourceTruth",
    phase: "evidence",
    priority: 20,
    module: "./engines/sourceTruthEngine.js",
    exportName: "analyzeSourceTruthBatch",
    dependsOn: ["projectIdentity"],
    inputContract: {
      requiredAny: [["source", "discoverySources", "sourceTruth", "evidence"]],
      optional: ["providerHealth", "evidenceQualityScore"],
    },
    outputContract: {
      requiredAny: [["sourceTruthScore", "sourceTruthVerdict", "sourceTruth"]],
      scoreFields: ["sourceTruthScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: false,
  },
  {
    id: "activeLiquidityTruth",
    phase: "liquidity",
    priority: 30,
    module: "./engines/activeLiquidityTruthEngine.js",
    exportName: "analyzeActiveLiquidityTruthBatch",
    dependsOn: ["projectIdentity"],
    inputContract: {
      requiredAny: [["liquidityUsd", "liquidity", "pairAddress"]],
      optional: ["volume24h", "hardExitLiquidityUsd"],
    },
    outputContract: {
      requiredAny: [["activeLiquidityTruthScore", "activeLiquidityTruthVerdict"]],
      scoreFields: ["activeLiquidityTruthScore", "liquidityControlRisk"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "organicBuyerClassifier",
    phase: "buyers",
    priority: 40,
    module: "./engines/organicBuyerClassifierEngine.js",
    exportName: "analyzeOrganicBuyerClassifierBatch",
    dependsOn: ["activeLiquidityTruth"],
    inputContract: {
      requiredAny: [["buyers24h", "buyTransactions24h", "organicBuyerScore", "holderGrowthScore"]],
      optional: ["walletClusters", "holderGrowthScore", "volume24h"],
    },
    outputContract: {
      requiredAny: [["organicBuyerScore", "organicBuyerVerdict"]],
      scoreFields: ["organicBuyerScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: false,
  },
  {
    id: "walletCluster",
    phase: "wallets",
    priority: 50,
    module: "./engines/walletClusterEngine.js",
    exportName: "analyzeWalletClusterBatch",
    dependsOn: ["projectIdentity"],
    inputContract: {
      requiredAny: [["wallets", "holders", "walletClusterRiskScore", "smartWalletScore"]],
      optional: ["buyers24h", "deployer", "ownerAddress"],
    },
    outputContract: {
      requiredAny: [["walletClusterScore", "walletClusterRiskScore", "walletClusterVerdict"]],
      scoreFields: ["walletClusterScore", "walletClusterRiskScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "instantSafetyGate",
    phase: "safety",
    priority: 60,
    module: "./engines/instantSafetyGateEngine.js",
    exportName: "analyzeInstantSafetyGateBatch",
    dependsOn: ["projectIdentity", "activeLiquidityTruth"],
    inputContract: {
      requiredAny: [["address", "contractVerified", "instantSafetyStatus", "riskScore"]],
      optional: ["ownerRenounced", "honeypot", "tax", "mintAuthority"],
    },
    outputContract: {
      requiredAny: [["instantSafetyStatus", "instantSafetyScore", "instantSafetyRiskScore"]],
      scoreFields: ["instantSafetyScore", "instantSafetyRiskScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "block-on-critical",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "contractAuthorityRisk",
    phase: "safety",
    priority: 65,
    module: "./engines/contractAuthorityRiskEngine.js",
    exportName: "analyzeContractAuthorityRiskBatch",
    dependsOn: ["projectIdentity", "instantSafetyGate"],
    inputContract: {
      requiredAny: [["securityEvidenceSummary", "securityEvidence", "address", "contractAddress"]],
      optional: ["chain", "ownerRenounced", "contractVerified", "honeypotRiskScore"],
    },
    outputContract: {
      requiredAny: [["contractAuthorityRiskScore", "contractAuthoritySafetyScore", "contractAuthorityVerdict"]],
      scoreFields: ["contractAuthorityRiskScore", "contractAuthoritySafetyScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "block-on-critical",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "liquidityControlRisk",
    phase: "liquidity",
    priority: 66,
    module: "./engines/liquidityControlRiskEngine.js",
    exportName: "analyzeLiquidityControlRiskBatch",
    dependsOn: ["activeLiquidityTruth"],
    inputContract: {
      requiredAny: [["liquidityUsd", "liquidity", "lpLockedPct", "lpBurnedPct"]],
      optional: ["lpRemovalUsd", "ownerLpSharePct", "securityEvidenceSummary"],
    },
    outputContract: {
      requiredAny: [["liquidityControlRiskScore", "liquidityControlSafetyScore", "liquidityControlVerdict"]],
      scoreFields: ["liquidityControlRiskScore", "liquidityControlSafetyScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "organicDemandIntegrity",
    phase: "safety",
    priority: 70,
    module: "./engines/organicDemandIntegrityEngine.js",
    exportName: "analyzeOrganicDemandIntegrityBatch",
    dependsOn: ["activeLiquidityTruth", "organicBuyerClassifier", "walletCluster"],
    inputContract: {
      requiredAny: [["liquidityUsd", "volume24h", "organicBuyerScore", "organicDemandScore"]],
      optional: ["holders", "buyers24h", "sellPressureScore"],
    },
    outputContract: {
      requiredAny: [
        ["organicDemandVerdict", "organicEconomicIntegrityScore", "economicIntegrityRiskScore"],
      ],
      scoreFields: [
        "organicEconomicIntegrityScore",
        "economicIntegrityRiskScore",
        "activityAuthenticityRiskScore",
        "supplyIntegrityRiskScore",
      ],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "githubIntelligencePro",
    phase: "development",
    priority: 80,
    module: "./engines/githubIntelligenceProEngine.js",
    exportName: "analyzeGithubIntelligenceProBatch",
    dependsOn: ["projectIdentity"],
    inputContract: {
      requiredAny: [["githubRepo", "repository", "githubScore", "developerActivityScore"]],
      optional: ["githubStars", "githubCommits30d", "githubContributors"],
    },
    outputContract: {
      requiredAny: [["githubProScore", "githubProVerdict"]],
      scoreFields: ["githubProScore", "developerActivityScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: false,
  },
  {
    id: "roadmapCatalystProfit",
    phase: "catalyst",
    priority: 90,
    module: "./engines/roadmapCatalystProfitEngine.js",
    exportName: "analyzeRoadmapCatalystProfitBatch",
    dependsOn: ["sourceTruth"],
    inputContract: {
      requiredAny: [["roadmap", "description", "websiteText", "catalystScore", "liveCatalystEvents"]],
      optional: ["docsUrl", "milestones", "launchDate"],
    },
    outputContract: {
      requiredAny: [["roadmapProfitabilityScore", "roadmapCatalystVerdict", "roadmapMilestones"]],
      scoreFields: ["roadmapProfitabilityScore", "catalystScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: false,
  },
  {
    id: "discoveryDecision",
    phase: "decision-precheck",
    priority: 100,
    module: "./engines/discoveryDecisionEngine.js",
    exportName: "analyzeDiscoveryDecisionBatch",
    dependsOn: ["projectIdentity", "instantSafetyGate", "organicDemandIntegrity"],
    inputContract: {
      requiredAny: [["discoveryPriorityScore", "nativeDiscoveryScore", "sourceTruthScore"]],
      optional: ["candidateLifecycleStage", "organicDemandFirewallStatus"],
    },
    outputContract: {
      requiredAny: [["discoveryDecisionScore", "discoveryDecisionTier"]],
      scoreFields: ["discoveryDecisionScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "sniperEvidenceFamily",
    phase: "proof",
    priority: 110,
    module: "./engines/sniperEvidenceFamilyEngine.js",
    exportName: "analyzeSniperEvidenceFamiliesBatch",
    dependsOn: ["sourceTruth", "activeLiquidityTruth", "githubIntelligencePro"],
    inputContract: {
      requiredAny: [["sourceTruthScore", "liquidityUsd", "githubProScore", "organicBuyerScore"]],
      optional: ["catalystScore", "smartWalletScore", "developerActivityScore"],
    },
    outputContract: {
      requiredAny: [["sniperEvidenceFamilySummary", "sniperEvidenceConfidence"]],
      scoreFields: ["sniperEvidenceConfidence"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: false,
  },
  {
    id: "sniperIntegrityGate",
    phase: "final-gate",
    priority: 120,
    module: "./engines/sniperIntegrityGateEngine.js",
    exportName: "analyzeSniperIntegrityGateBatch",
    dependsOn: ["sniperEvidenceFamily", "instantSafetyGate", "activeLiquidityTruth"],
    inputContract: {
      requiredAny: [["sniperEvidenceFamilySummary", "sniperEvidenceConfidence", "finalQualified"]],
      optional: ["purchaseRouteConfirmed", "tokenUnlockRiskScore"],
    },
    outputContract: {
      requiredAny: [["sniperState", "sniperIntegrityScore", "sniperIntegrityBlockers"]],
      scoreFields: ["sniperIntegrityScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "block-on-critical",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "canonicalExecutionRoute",
    phase: "execution",
    priority: 128,
    module: "./engines/canonicalExecutionRouteEngine.js",
    exportName: "analyzeCanonicalExecutionRouteBatch",
    dependsOn: ["projectIdentity", "activeLiquidityTruth"],
    inputContract: {
      requiredAny: [["purchaseRoute", "executionRoute", "marketData", "source", "address", "contractAddress"]],
      optional: ["pairAddress", "poolAddress", "rawCandidate", "discoverySources", "url"],
    },
    outputContract: {
      requiredAny: [["canonicalExecutionRoute", "canonicalExecutionRouteStatus"]],
      scoreFields: ["canonicalExecutionRouteConfidence"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "executionProof",
    phase: "execution",
    priority: 129,
    module: "./engines/executionProofEngine.js",
    exportName: "analyzeExecutionProofBatch",
    dependsOn: ["canonicalExecutionRoute"],
    inputContract: {
      requiredAny: [["canonicalExecutionRoute", "purchaseRoute", "liquidityUsd", "address", "contractAddress"]],
      optional: ["pairAddress", "quoteTimestamp", "executionSlippagePct", "providerFailures"],
    },
    outputContract: {
      requiredAny: [["executionProof", "executionStatus", "moneyStatus", "moneyEvidence", "purchaseRouteConfirmed"]],
      scoreFields: ["moneyScore", "moneyConfidence"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "smallCapHunter",
    phase: "execution",
    priority: 130,
    module: "./engines/smallCapHunterEngine.js",
    exportName: "analyzeSmallCapHunterBatch",
    dependsOn: ["canonicalExecutionRoute", "executionProof"],
    inputContract: {
      requiredAny: [["canonicalExecutionRoute", "executionProof", "liquidityUsd", "volume24h", "marketCap"]],
      optional: ["proofScore", "githubProScore", "narrativeHeatScore", "trapRiskScore"],
    },
    outputContract: {
      requiredAny: [["smallCapHunter", "smallCapHunterScore", "smallCapHunterVerdict"]],
      scoreFields: ["smallCapHunterScore", "smallCapExecutionScore", "smallCapRiskScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "proofOfAlphaExecutionTwin",
    phase: "execution",
    priority: 131,
    module: "./engines/proofOfAlphaExecutionTwinEngine.js",
    exportName: "analyzeProofOfAlphaExecutionTwinBatch",
    dependsOn: ["executionProof", "smallCapHunter"],
    inputContract: {
      requiredAny: [["executionProof", "canonicalExecutionRoute", "smallCapHunter", "liquidityUsd"]],
      optional: ["slippagePct", "route", "preferredExchange"],
    },
    outputContract: {
      requiredAny: [["proofOfAlphaExecutionTwin", "proofOfAlphaExecutionTwinScore", "proofOfAlphaExecutionTwinVerdict"]],
      scoreFields: ["proofOfAlphaExecutionTwinScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "opportunityTiming",
    phase: "ranking",
    priority: 132,
    module: "./engines/opportunityTimingEngine.js",
    exportName: "analyzeOpportunityTimingBatch",
    dependsOn: ["acceleration", "momentumShift", "liquidityExpansion"],
    inputContract: {
      requiredAny: [["accelerationScore", "momentumCompressionScore", "buyPressureScore", "catalystScore"]],
      optional: ["priceChange24h", "priceChange7d", "smartWalletArrivalScore", "liquidityExpansionScore"],
    },
    outputContract: {
      requiredAny: [["opportunityTimingScore", "opportunityTimingLevel", "opportunityTimingComponents"]],
      scoreFields: ["opportunityTimingScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: false,
  },
  {
    id: "attentionGap",
    phase: "ranking",
    priority: 133,
    module: "./engines/attentionGapEngine.js",
    exportName: "analyzeAttentionGapBatch",
    dependsOn: ["developerActivity", "liquidityExpansion", "sourceTruth"],
    inputContract: {
      requiredAny: [["developerActivityScore", "githubProScore", "liquidityExpansionScore", "buyPressureScore"]],
      optional: ["xSocialScore", "externalSignalScore", "exchangeProbabilityScore"],
    },
    outputContract: {
      requiredAny: [["attentionGapScore", "attentionGapLevel", "attentionGapComponents"]],
      scoreFields: ["attentionGapScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: false,
  },
  {
    id: "progressiveOpportunityRanking",
    phase: "ranking",
    priority: 135,
    module: "./engines/progressiveOpportunityRankingEngine.js",
    exportName: "analyzeProgressiveOpportunityRankingBatch",
    dependsOn: ["sourceTruth", "sniperIntegrityGate", "proofOfAlphaExecutionTwin", "executionProof"],
    inputContract: {
      requiredAny: [["pipelineScore", "accelerationScore", "liquidityExpansionScore", "sourceTruthScore"]],
      optional: ["finalSelectionState", "purchaseRouteConfirmed", "institutionalDataProvenanceScore"],
    },
    outputContract: {
      requiredAny: [["opportunityRankingTier", "bestAvailableEligible", "moneyRankEligible", "missingEvidence"]],
      scoreFields: [
        "progressiveOpportunityScore",
        "trustScore",
        "executionScore",
        "moneyRankScore",
        "opportunityEvidenceCoverage",
      ],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: true,
  },
  {
    id: "marketOpportunityRank",
    phase: "ranking",
    priority: 136,
    module: "./engines/marketOpportunityRankEngine.js",
    exportName: "analyzeMarketOpportunityRankBatch",
    dependsOn: ["progressiveOpportunityRanking", "opportunityTiming", "attentionGap"],
    inputContract: {
      requiredAny: [["progressiveOpportunityScore", "opportunityTimingScore", "trustScore", "attentionGapScore"]],
      optional: ["localAIStatus", "localAIVerdict", "opportunityEvidenceCoverage"],
    },
    outputContract: {
      requiredAny: [["marketOpportunityRank", "opportunityEvidenceRecord", "timeHorizonScores"]],
      scoreFields: ["marketOpportunityRank", "localAIConsensusScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: false,
  },
  {
    id: "marketOpportunityLearning",
    phase: "learning",
    priority: 137,
    module: "./engines/marketOpportunityLearningEngine.js",
    exportName: "analyzeMarketOpportunityLearningBatch",
    dependsOn: ["marketOpportunityRank"],
    inputContract: {
      requiredAny: [["marketOpportunityRank", "opportunityEvidenceRecord", "recommendedHorizon"]],
      optional: ["priceUsd", "liquidityUsd", "localAIConsensusScore"],
    },
    outputContract: {
      requiredAny: [["marketOpportunityLearningScore", "marketOpportunityLearningConfidence", "learnedMarketOpportunityRank"]],
      scoreFields: ["marketOpportunityLearningScore", "learnedMarketOpportunityRank"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: false,
  },
  {
    id: "sevenDayTenXResearch",
    phase: "ranking",
    priority: 138,
    module: "./engines/sevenDayTenXResearchEngine.js",
    exportName: "analyzeSevenDayTenXResearchBatch",
    dependsOn: ["marketOpportunityLearning", "progressiveOpportunityRanking", "sniperIntegrityGate"],
    inputContract: {
      requiredAny: [["marketCap", "fdv", "circulatingMarketCapUsd"], ["liquidityUsd", "dexLiquidityUsd", "stableExitLiquidityUsd"]],
      optional: ["contractAddress", "tokenAddress", "pairAddress", "purchaseRouteConfirmed", "instantSafetyStatus"],
    },
    outputContract: {
      requiredAny: [["sevenDayTenXScore", "sevenDayTenXVerdict", "sevenDayTenX"]],
      scoreFields: ["sevenDayTenXScore", "sevenDayTenXRawScore", "sevenDayTenXModeledScenarioPct"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: false,
  },
  {
    id: "alphaEvolutionGovernor",
    phase: "governor",
    priority: 140,
    module: "./engines/alphaEvolutionGovernorEngine.js",
    exportName: "analyzeAlphaEvolutionGovernorBatch",
    dependsOn: ["sourceTruth", "sniperIntegrityGate", "proofOfAlphaExecutionTwin"],
    inputContract: {
      requiredAny: [["alphaEvolutionGovernorScore", "pipelineScore", "institutionalScore"]],
      optional: ["alphaContractScore", "paperTradingOutcomeScore", "sourceTruthScore"],
    },
    outputContract: {
      requiredAny: [["alphaEvolutionGovernorScore", "alphaEvolutionGovernorVerdict"]],
      scoreFields: ["alphaEvolutionGovernorScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: false,
  },
];

export function getEngineContracts() {
  return [...ENGINE_CONTRACTS].sort((a, b) => a.priority - b.priority);
}

export function getContractsByPhase() {
  return getEngineContracts().reduce((acc, contract) => {
    acc[contract.phase] = acc[contract.phase] || [];
    acc[contract.phase].push(contract);
    return acc;
  }, {});
}

export function findEngineContract(id = "") {
  return getEngineContracts().find((contract) => contract.id === id) || null;
}
