export const ENGINE_CONTRACTS = [
  {
    id: "projectIdentity",
    phase: "identity",
    priority: 10,
    module: "./engines/projectIdentityEngine.js",
    exportName: "analyzeProjectIdentityBatch",
    dependsOn: [],
    inputContract: {
      requiredAny: [["address", "pairAddress", "symbol", "name"]],
      optional: ["chain", "url", "website", "twitterHandle", "githubRepo"],
    },
    outputContract: {
      requiredAny: [["projectIdentityVerdict", "identityResolutionScore", "projectIdentity"]],
      scoreFields: ["identityResolutionScore", "identityRiskScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "sourceTruth",
    phase: "evidence",
    priority: 20,
    module: "./engines/sourceTruthEngine.js",
    exportName: "analyzeSourceTruthBatch",
    dependsOn: ["projectIdentity"],
    inputContract: {
      requiredAny: [["source", "discoverySources", "sourceTruth", "evidence"]],
      optional: ["providerHealth", "evidenceQualityScore"],
    },
    outputContract: {
      requiredAny: [["sourceTruthScore", "sourceTruthVerdict", "sourceTruth"]],
      scoreFields: ["sourceTruthScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: false,
  },
  {
    id: "activeLiquidityTruth",
    phase: "liquidity",
    priority: 30,
    module: "./engines/activeLiquidityTruthEngine.js",
    exportName: "analyzeActiveLiquidityTruthBatch",
    dependsOn: ["projectIdentity"],
    inputContract: {
      requiredAny: [["liquidityUsd", "liquidity", "pairAddress"]],
      optional: ["volume24h", "hardExitLiquidityUsd"],
    },
    outputContract: {
      requiredAny: [["activeLiquidityTruthScore", "activeLiquidityTruthVerdict"]],
      scoreFields: ["activeLiquidityTruthScore", "liquidityControlRisk"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "organicBuyerClassifier",
    phase: "buyers",
    priority: 40,
    module: "./engines/organicBuyerClassifierEngine.js",
    exportName: "analyzeOrganicBuyerClassifierBatch",
    dependsOn: ["activeLiquidityTruth"],
    inputContract: {
      requiredAny: [["buyers24h", "buyTransactions24h", "organicBuyerScore", "holderGrowthScore"]],
      optional: ["walletClusters", "holderGrowthScore", "volume24h"],
    },
    outputContract: {
      requiredAny: [["organicBuyerScore", "organicBuyerVerdict"]],
      scoreFields: ["organicBuyerScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: false,
  },
  {
    id: "walletCluster",
    phase: "wallets",
    priority: 50,
    module: "./engines/walletClusterEngine.js",
    exportName: "analyzeWalletClusterBatch",
    dependsOn: ["projectIdentity"],
    inputContract: {
      requiredAny: [["wallets", "holders", "walletClusterRiskScore", "smartWalletScore"]],
      optional: ["buyers24h", "deployer", "ownerAddress"],
    },
    outputContract: {
      requiredAny: [["walletClusterScore", "walletClusterRiskScore", "walletClusterVerdict"]],
      scoreFields: ["walletClusterScore", "walletClusterRiskScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "instantSafetyGate",
    phase: "safety",
    priority: 60,
    module: "./engines/instantSafetyGateEngine.js",
    exportName: "analyzeInstantSafetyGateBatch",
    dependsOn: ["projectIdentity", "activeLiquidityTruth"],
    inputContract: {
      requiredAny: [["address", "contractVerified", "instantSafetyStatus", "riskScore"]],
      optional: ["ownerRenounced", "honeypot", "tax", "mintAuthority"],
    },
    outputContract: {
      requiredAny: [["instantSafetyStatus", "instantSafetyScore", "instantSafetyRiskScore"]],
      scoreFields: ["instantSafetyScore", "instantSafetyRiskScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "block-on-critical",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "contractAuthorityRisk",
    phase: "safety",
    priority: 65,
    module: "./engines/contractAuthorityRiskEngine.js",
    exportName: "analyzeContractAuthorityRiskBatch",
    dependsOn: ["projectIdentity", "instantSafetyGate"],
    inputContract: {
      requiredAny: [["securityEvidenceSummary", "securityEvidence", "address", "contractAddress"]],
      optional: ["chain", "ownerRenounced", "contractVerified", "honeypotRiskScore"],
    },
    outputContract: {
      requiredAny: [["contractAuthorityRiskScore", "contractAuthoritySafetyScore", "contractAuthorityVerdict"]],
      scoreFields: ["contractAuthorityRiskScore", "contractAuthoritySafetyScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "block-on-critical",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "liquidityControlRisk",
    phase: "liquidity",
    priority: 66,
    module: "./engines/liquidityControlRiskEngine.js",
    exportName: "analyzeLiquidityControlRiskBatch",
    dependsOn: ["activeLiquidityTruth"],
    inputContract: {
      requiredAny: [["liquidityUsd", "liquidity", "lpLockedPct", "lpBurnedPct"]],
      optional: ["lpRemovalUsd", "ownerLpSharePct", "securityEvidenceSummary"],
    },
    outputContract: {
      requiredAny: [["liquidityControlRiskScore", "liquidityControlSafetyScore", "liquidityControlVerdict"]],
      scoreFields: ["liquidityControlRiskScore", "liquidityControlSafetyScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "organicDemandIntegrity",
    phase: "safety",
    priority: 70,
    module: "./engines/organicDemandIntegrityEngine.js",
    exportName: "analyzeOrganicDemandIntegrityBatch",
    dependsOn: ["activeLiquidityTruth", "organicBuyerClassifier", "walletCluster"],
    inputContract: {
      requiredAny: [["liquidityUsd", "volume24h", "organicBuyerScore", "organicDemandScore"]],
      optional: ["holders", "buyers24h", "sellPressureScore"],
    },
    outputContract: {
      requiredAny: [
        ["organicDemandVerdict", "organicEconomicIntegrityScore", "economicIntegrityRiskScore"],
      ],
      scoreFields: [
        "organicEconomicIntegrityScore",
        "economicIntegrityRiskScore",
        "activityAuthenticityRiskScore",
        "supplyIntegrityRiskScore",
      ],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "developerActivity",
    phase: "development",
    priority: 79,
    module: "./engines/developerActivityEngine.js",
    exportName: "analyzeDeveloperActivityBatch",
    dependsOn: [],
    inputContract: {
      requiredAny: [["github", "githubUrl", "repository", "commits30d", "contributors", "githubQualityScore"]],
      optional: ["releases", "openIssues", "closedIssues30d"],
    },
    outputContract: {
      requiredAny: [["developerActivityScore"], ["developerActivity", "developerScore"]],
      scoreFields: ["developerActivityScore", "developerScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: false,
  },
  {
    id: "githubIntelligencePro",
    phase: "development",
    priority: 80,
    module: "./engines/githubIntelligenceProEngine.js",
    exportName: "analyzeGithubIntelligenceProBatch",
    dependsOn: ["projectIdentity"],
    inputContract: {
      requiredAny: [["githubRepo", "repository", "githubScore", "developerActivityScore"]],
      optional: ["githubStars", "githubCommits30d", "githubContributors"],
    },
    outputContract: {
      requiredAny: [["githubProScore", "githubProVerdict"]],
      scoreFields: ["githubProScore", "developerActivityScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: false,
  },
  {
    id: "roadmapCatalystProfit",
    phase: "catalyst",
    priority: 90,
    module: "./engines/roadmapCatalystProfitEngine.js",
    exportName: "analyzeRoadmapCatalystProfitBatch",
    dependsOn: ["sourceTruth"],
    inputContract: {
      requiredAny: [["roadmap", "description", "websiteText", "catalystScore", "liveCatalystEvents"]],
      optional: ["docsUrl", "milestones", "launchDate"],
    },
    outputContract: {
      requiredAny: [["roadmapProfitabilityScore", "roadmapCatalystVerdict", "roadmapMilestones"]],
      scoreFields: ["roadmapProfitabilityScore", "catalystScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: false,
  },
  {
    id: "discoveryDecision",
    phase: "decision-precheck",
    priority: 100,
    module: "./engines/discoveryDecisionEngine.js",
    exportName: "analyzeDiscoveryDecisionBatch",
    dependsOn: ["projectIdentity", "instantSafetyGate", "organicDemandIntegrity"],
    inputContract: {
      requiredAny: [["discoveryPriorityScore", "nativeDiscoveryScore", "sourceTruthScore"]],
      optional: ["candidateLifecycleStage", "organicDemandFirewallStatus"],
    },
    outputContract: {
      requiredAny: [["discoveryDecisionScore", "discoveryDecisionTier"]],
      scoreFields: ["discoveryDecisionScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "sniperEvidenceFamily",
    phase: "proof",
    priority: 110,
    module: "./engines/sniperEvidenceFamilyEngine.js",
    exportName: "analyzeSniperEvidenceFamiliesBatch",
    dependsOn: ["sourceTruth", "activeLiquidityTruth", "githubIntelligencePro"],
    inputContract: {
      requiredAny: [["sourceTruthScore", "liquidityUsd", "githubProScore", "organicBuyerScore"]],
      optional: ["catalystScore", "smartWalletScore", "developerActivityScore"],
    },
    outputContract: {
      requiredAny: [["sniperEvidenceFamilySummary", "sniperEvidenceConfidence"]],
      scoreFields: ["sniperEvidenceConfidence"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: false,
  },
  {
    id: "sniperIntegrityGate",
    phase: "final-gate",
    priority: 120,
    module: "./engines/sniperIntegrityGateEngine.js",
    exportName: "analyzeSniperIntegrityGateBatch",
    dependsOn: ["sniperEvidenceFamily", "instantSafetyGate", "activeLiquidityTruth"],
    inputContract: {
      requiredAny: [["sniperEvidenceFamilySummary", "sniperEvidenceConfidence", "finalQualified"]],
      optional: ["purchaseRouteConfirmed", "tokenUnlockRiskScore"],
    },
    outputContract: {
      requiredAny: [["sniperState", "sniperIntegrityScore", "sniperIntegrityBlockers"]],
      scoreFields: ["sniperIntegrityScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "block-on-critical",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "acceleration",
    phase: "ranking",
    priority: 121,
    module: "./engines/accelerationEngine.js",
    exportName: "analyzeAccelerationBatch",
    dependsOn: [],
    inputContract: {
      requiredAny: [["velocity", "previousVolumeVelocity", "previousLiquidityVelocity", "previousHolderVelocity"]],
      optional: ["previousFollowerVelocity", "previousDeveloperVelocity", "previousSmartWalletVelocity"],
    },
    outputContract: {
      requiredAny: [["accelerationScore"], ["acceleration", "accelerationLevel"]],
      scoreFields: ["accelerationScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: false,
  },
  {
    id: "canonicalExecutionRoute",
    phase: "execution",
    priority: 128,
    module: "./engines/canonicalExecutionRouteEngine.js",
    exportName: "analyzeCanonicalExecutionRouteBatch",
    dependsOn: ["projectIdentity", "activeLiquidityTruth"],
    inputContract: {
      requiredAny: [["purchaseRoute", "executionRoute", "marketData", "source", "address", "contractAddress"]],
      optional: ["pairAddress", "poolAddress", "rawCandidate", "discoverySources", "url"],
    },
    outputContract: {
      requiredAny: [["canonicalExecutionRoute", "canonicalExecutionRouteStatus"]],
      scoreFields: ["canonicalExecutionRouteConfidence"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "executionProof",
    phase: "execution",
    priority: 129,
    module: "./engines/executionProofEngine.js",
    exportName: "analyzeExecutionProofBatch",
    dependsOn: ["canonicalExecutionRoute"],
    inputContract: {
      requiredAny: [["canonicalExecutionRoute", "purchaseRoute", "liquidityUsd", "address", "contractAddress"]],
      optional: ["pairAddress", "quoteTimestamp", "executionSlippagePct", "providerFailures"],
    },
    outputContract: {
      requiredAny: [["executionProof", "executionStatus", "moneyStatus", "moneyEvidence", "purchaseRouteConfirmed"]],
      scoreFields: ["moneyScore", "moneyConfidence"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "smallCapHunter",
    phase: "execution",
    priority: 130,
    module: "./engines/smallCapHunterEngine.js",
    exportName: "analyzeSmallCapHunterBatch",
    dependsOn: ["canonicalExecutionRoute", "executionProof"],
    inputContract: {
      requiredAny: [["canonicalExecutionRoute", "executionProof", "liquidityUsd", "volume24h", "marketCap"]],
      optional: ["proofScore", "githubProScore", "narrativeHeatScore", "trapRiskScore"],
    },
    outputContract: {
      requiredAny: [["smallCapHunter", "smallCapHunterScore", "smallCapHunterVerdict"]],
      scoreFields: ["smallCapHunterScore", "smallCapExecutionScore", "smallCapRiskScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "proofOfAlphaExecutionTwin",
    phase: "execution",
    priority: 131,
    module: "./engines/proofOfAlphaExecutionTwinEngine.js",
    exportName: "analyzeProofOfAlphaExecutionTwinBatch",
    dependsOn: ["executionProof", "smallCapHunter"],
    inputContract: {
      requiredAny: [["executionProof", "canonicalExecutionRoute", "smallCapHunter", "liquidityUsd"]],
      optional: ["slippagePct", "route", "preferredExchange"],
    },
    outputContract: {
      requiredAny: [["proofOfAlphaExecutionTwin", "proofOfAlphaExecutionTwinScore", "proofOfAlphaExecutionTwinVerdict"]],
      scoreFields: ["proofOfAlphaExecutionTwinScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "liquidityExpansion",
    phase: "liquidity",
    priority: 131.2,
    module: "./engines/liquidityExpansionEngine.js",
    exportName: "analyzeLiquidityExpansionBatch",
    dependsOn: [],
    inputContract: {
      requiredAny: [["liquidityUsd", "dexLiquidityUsd", "stableExitLiquidityUsd"]],
      optional: ["previousLiquidityUsd", "volume24h", "volume24hUsd"],
    },
    outputContract: {
      requiredAny: [["liquidityExpansionScore"], ["liquidityExpansion", "liquidityExpansionLevel"]],
      scoreFields: ["liquidityExpansionScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: false,
  },
  {
    id: "momentumShift",
    phase: "ranking",
    priority: 131.4,
    module: "./engines/momentumShiftEngine.js",
    exportName: "analyzeMomentumShiftBatch",
    dependsOn: ["acceleration", "liquidityExpansion"],
    inputContract: {
      requiredAny: [["priceChange24h", "priceChange24hPct", "volume24h", "volume24hUsd", "buyPressureScore"]],
      optional: ["liquidityUsd", "buyTransactions24h", "sellTransactions24h", "earlyBreakoutScore", "relativeStrengthScore"],
    },
    outputContract: {
      requiredAny: [["momentumShiftScore"], ["momentumShiftLevel"]],
      scoreFields: ["momentumShiftScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: false,
  },
  {
    id: "opportunityTiming",
    phase: "ranking",
    priority: 132,
    module: "./engines/opportunityTimingEngine.js",
    exportName: "analyzeOpportunityTimingBatch",
    dependsOn: ["acceleration", "momentumShift", "liquidityExpansion"],
    inputContract: {
      requiredAny: [["accelerationScore", "momentumCompressionScore", "buyPressureScore", "catalystScore"]],
      optional: ["priceChange24h", "priceChange7d", "smartWalletArrivalScore", "liquidityExpansionScore"],
    },
    outputContract: {
      requiredAny: [["opportunityTimingScore", "opportunityTimingLevel", "opportunityTimingComponents"]],
      scoreFields: ["opportunityTimingScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: false,
  },
  {
    id: "attentionGap",
    phase: "ranking",
    priority: 133,
    module: "./engines/attentionGapEngine.js",
    exportName: "analyzeAttentionGapBatch",
    dependsOn: ["developerActivity", "liquidityExpansion", "sourceTruth"],
    inputContract: {
      requiredAny: [["developerActivityScore", "githubProScore", "liquidityExpansionScore", "buyPressureScore"]],
      optional: ["xSocialScore", "externalSignalScore", "exchangeProbabilityScore"],
    },
    outputContract: {
      requiredAny: [["attentionGapScore", "attentionGapLevel", "attentionGapComponents"]],
      scoreFields: ["attentionGapScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: false,
  },
  {
    id: "progressiveOpportunityRanking",
    phase: "ranking",
    priority: 135,
    module: "./engines/progressiveOpportunityRankingEngine.js",
    exportName: "analyzeProgressiveOpportunityRankingBatch",
    dependsOn: ["sourceTruth", "sniperIntegrityGate", "proofOfAlphaExecutionTwin", "executionProof"],
    inputContract: {
      requiredAny: [["pipelineScore", "accelerationScore", "liquidityExpansionScore", "sourceTruthScore"]],
      optional: ["finalSelectionState", "purchaseRouteConfirmed", "institutionalDataProvenanceScore"],
    },
    outputContract: {
      requiredAny: [["opportunityRankingTier", "bestAvailableEligible", "moneyRankEligible", "missingEvidence"]],
      scoreFields: [
        "progressiveOpportunityScore",
        "trustScore",
        "executionScore",
        "moneyRankScore",
        "opportunityEvidenceCoverage",
      ],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: true,
  },
  {
    id: "marketOpportunityRank",
    phase: "ranking",
    priority: 136,
    module: "./engines/marketOpportunityRankEngine.js",
    exportName: "analyzeMarketOpportunityRankBatch",
    dependsOn: ["progressiveOpportunityRanking", "opportunityTiming", "attentionGap"],
    inputContract: {
      requiredAny: [["progressiveOpportunityScore", "opportunityTimingScore", "trustScore", "attentionGapScore"]],
      optional: ["localAIStatus", "localAIVerdict", "opportunityEvidenceCoverage"],
    },
    outputContract: {
      requiredAny: [["marketOpportunityRank", "opportunityEvidenceRecord", "timeHorizonScores"]],
      scoreFields: ["marketOpportunityRank", "localAIConsensusScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: false,
  },
  {
    id: "marketOpportunityLearning",
    phase: "learning",
    priority: 137,
    module: "./engines/marketOpportunityLearningEngine.js",
    exportName: "analyzeMarketOpportunityLearningBatch",
    dependsOn: ["marketOpportunityRank"],
    inputContract: {
      requiredAny: [["marketOpportunityRank", "opportunityEvidenceRecord", "recommendedHorizon"]],
      optional: ["priceUsd", "liquidityUsd", "localAIConsensusScore"],
    },
    outputContract: {
      requiredAny: [["marketOpportunityLearningScore", "marketOpportunityLearningConfidence", "learnedMarketOpportunityRank"]],
      scoreFields: ["marketOpportunityLearningScore", "learnedMarketOpportunityRank"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: false,
  },
  {
    id: "sevenDayTenXResearch",
    phase: "ranking",
    priority: 138,
    module: "./engines/sevenDayTenXResearchEngine.js",
    exportName: "analyzeSevenDayTenXResearchBatch",
    dependsOn: ["marketOpportunityLearning", "progressiveOpportunityRanking", "sniperIntegrityGate"],
    inputContract: {
      requiredAny: [["marketCap", "fdv", "circulatingMarketCapUsd"], ["liquidityUsd", "dexLiquidityUsd", "stableExitLiquidityUsd"]],
      optional: ["contractAddress", "tokenAddress", "pairAddress", "purchaseRouteConfirmed", "instantSafetyStatus"],
    },
    outputContract: {
      requiredAny: [["sevenDayTenXScore", "sevenDayTenXVerdict", "sevenDayTenX"]],
      scoreFields: ["sevenDayTenXScore", "sevenDayTenXRawScore", "sevenDayTenXModeledScenarioPct"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: false,
  },
  {
    id: "scalpMicrostructure",
    phase: "execution",
    priority: 139,
    module: "./engines/scalpMicrostructureEngine.js",
    exportName: "analyzeScalpMicrostructureBatch",
    dependsOn: ["sevenDayTenXResearch", "routeAccessibility", "sniperIntegrityGate"],
    inputContract: {
      requiredAny: [["liquidityUsd", "dexLiquidityUsd", "stableExitLiquidityUsd"], ["purchaseRouteConfirmed", "executionStatus", "executionProof"]],
      optional: ["sellRouteAvailable", "spreadPct", "estimatedSlippagePct", "quoteAgeSeconds", "priceChange24hPct", "priceChange7dPct"],
    },
    outputContract: {
      requiredAny: [["scalpMicrostructureScore", "scalpMicrostructureLane", "scalpMicrostructure"]],
      scoreFields: ["scalpMicrostructureScore", "scalpEstimatedTotalCostPct"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: true,
  },
  {
    id: "routeAccessibility",
    phase: "execution",
    priority: 129.5,
    module: "./engines/routeAccessibilityEngine.js",
    exportName: "analyzeRouteAccessibilityBatch",
    dependsOn: ["canonicalExecutionRoute", "executionProof"],
    inputContract: {
      requiredAny: [["canonicalExecutionRoute", "executionProof", "purchaseRouteConfirmed", "routeTruthStatus"]],
      optional: ["coinbaseAvailable", "metamaskCompatible", "alternativeRoutes", "quoteAgeSeconds", "userRegion"],
    },
    outputContract: {
      requiredAny: [["routeAccessibility"], ["globalRouteQualityScore", "userAccessibilityScore"], ["executionReady", "userAccessible"]],
      scoreFields: ["globalRouteQualityScore", "userAccessibilityScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "utilityQuality",
    phase: "quality",
    priority: 137.5,
    module: "./engines/utilityQualityEngine.js",
    exportName: "analyzeUtilityQualityBatch",
    dependsOn: ["sourceTruth", "githubIntelligencePro", "roadmapCatalystProfit"],
    inputContract: {
      requiredAny: [["description", "websiteText", "roadmap", "githubRepo", "developerActivityScore"]],
      optional: ["utilityQualityScore", "realUtilityScore", "ecosystemIntegrationScore", "tokenomicsScore"],
    },
    outputContract: {
      requiredAny: [["utilityQualityScore"], ["utilityClassification", "realUtilityQualified"]],
      scoreFields: ["utilityQualityScore", "realUtilityScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: false,
  },
  {
    id: "preBreakoutSequence",
    phase: "ranking",
    priority: 137.6,
    module: "./engines/preBreakoutSequenceEngine.js",
    exportName: "analyzePreBreakoutSequenceBatch",
    dependsOn: ["liquidityExpansion"],
    inputContract: {
      requiredAny: [["priceChange24h", "priceChange24hPct", "volumeAcceleration", "buyerBreadthAccelerationScore", "liquidityFormationScore", "liquidityExpansionScore"]],
      optional: ["priceChange1hPct", "priceChange6hPct", "priceChange3dPct", "priceChange7dPct", "developerAccelerationV2Score", "socialAccelerationScore"],
    },
    outputContract: {
      requiredAny: [["preBreakoutSequenceScore"], ["preBreakoutTimingState", "timingState"]],
      scoreFields: ["preBreakoutSequenceScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: false,
  },
  {
    id: "earlyAsymmetryTriage",
    phase: "ranking",
    priority: 137.7,
    module: "./engines/earlyAsymmetryTriageEngine.js",
    exportName: "analyzeEarlyAsymmetryTriageBatch",
    dependsOn: ["sourceTruth", "activeLiquidityTruth", "preBreakoutSequence"],
    inputContract: {
      requiredAny: [
        ["circulatingMarketCapUsd", "marketCap", "marketData.marketCap", "rawCandidate.marketCap"],
        ["liquidityUsd", "dexLiquidityUsd", "stableExitLiquidityUsd", "marketData.liquidityUsd", "rawCandidate.liquidityUsd"],
        ["volume24hUsd", "volume24h", "marketData.volume24h", "rawCandidate.volume24h"],
      ],
      optional: ["buyerBreadthAccelerationScore", "attentionGapScore", "smartWalletNoveltyScore", "developerAccelerationV2Score", "catalystScore"],
    },
    outputContract: {
      requiredAny: [["earlyAsymmetryResearchPriorityScore"], ["earlyAsymmetryCoveragePct"], ["earlyAsymmetryConfidenceState"]],
      scoreFields: ["earlyAsymmetryResearchPriorityScore", "earlyAsymmetryResearchPriorityRawScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: false,
  },
  {
    id: "preBreakoutRadar",
    phase: "ranking",
    priority: 137.8,
    module: "./engines/preBreakoutRadarEngine.js",
    exportName: "analyzePreBreakoutRadarBatch",
    dependsOn: ["earlyAsymmetryTriage", "preBreakoutSequence"],
    inputContract: {
      requiredAny: [["earlyAsymmetryResearchPriorityScore", "preBreakoutSequenceScore", "scalpMicrostructureScore"]],
      optional: ["buyerBreadthAccelerationScore", "liquidityFormationScore", "attentionGapV2Score", "smartWalletNoveltyScore"],
    },
    outputContract: {
      requiredAny: [["preBreakoutRadarScore", "preBreakoutRadarLane", "preBreakoutRadar"]],
      scoreFields: ["preBreakoutRadarScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: true,
  },
  {
    id: "highUpsideScalpClassification",
    phase: "decision-reporting",
    priority: 139.8,
    module: "./engines/highUpsideScalpClassificationEngine.js",
    exportName: "analyzeHighUpsideScalpClassificationBatch",
    dependsOn: ["sevenDayTenXResearch", "scalpMicrostructure", "utilityQuality", "preBreakoutRadar"],
    inputContract: {
      requiredAny: [["sevenDayTenXScore", "preBreakoutRadarScore", "earlyAsymmetryResearchPriorityScore"], ["scalpMicrostructureScore", "executionProof", "routeTruthStatus"]],
      optional: ["utilityQualityScore", "capitalMigrationScore", "buyerBreadthAccelerationScore", "highUpsideScalpLane"],
    },
    outputContract: {
      requiredAny: [["highUpsideScalpScore"], ["highUpsideScalpLane"]],
      scoreFields: ["highUpsideScalpScore", "highUpsideScalpDataCoverage"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: true,
  },
  {
    id: "dailyCapitalMove",
    phase: "decision-reporting",
    priority: 139.9,
    module: "./engines/dailyCapitalMoveEngine.js",
    exportName: "analyzeDailyCapitalMoveBatch",
    dependsOn: ["highUpsideScalpClassification", "scalpMicrostructure", "routeAccessibility", "utilityQuality"],
    inputContract: {
      requiredAny: [
        ["highUpsideScalpScore", "hottestTenNowScore", "sevenDayTenXScore", "earlyAsymmetryResearchPriorityScore"],
        ["routeTruthStatus", "executionProofState", "executionProof", "canonicalExecutionRoute"],
        ["utilityQualityScore", "realUtilityScore", "utilityClassification"],
      ],
      optional: ["capitalMigrationScore", "buyerBreadthAccelerationScore", "liquidityFormationScore", "sourceTruthScore"],
    },
    outputContract: {
      requiredAny: [
        ["dailyCapitalMoveScore"],
        ["dailyCapitalMoveLane"],
        ["dailyCapitalMoveReason"],
        ["dailyCapitalMoveMissingProofCount", "dailyCapitalMoveMissingProof"],
      ],
      scoreFields: ["dailyCapitalMoveScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "alphaEvolutionGovernor",
    phase: "governor",
    priority: 140,
    module: "./engines/alphaEvolutionGovernorEngine.js",
    exportName: "analyzeAlphaEvolutionGovernorBatch",
    dependsOn: ["sourceTruth", "sniperIntegrityGate", "proofOfAlphaExecutionTwin"],
    inputContract: {
      requiredAny: [["alphaEvolutionGovernorScore", "pipelineScore", "institutionalScore"]],
      optional: ["alphaContractScore", "paperTradingOutcomeScore", "sourceTruthScore"],
    },
    outputContract: {
      requiredAny: [["alphaEvolutionGovernorScore", "alphaEvolutionGovernorVerdict"]],
      scoreFields: ["alphaEvolutionGovernorScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: false,
  },
];

export function getEngineContracts() {
  return [...ENGINE_CONTRACTS].sort((a, b) => a.priority - b.priority);
}

export function getContractsByPhase() {
  return getEngineContracts().reduce((acc, contract) => {
    acc[contract.phase] = acc[contract.phase] || [];
    acc[contract.phase].push(contract);
    return acc;
  }, {});
}

export function findEngineContract(id = "") {
  return getEngineContracts().find((contract) => contract.id === id) || null;
}
