export const ENGINE_CONTRACTS = [
  {
    id: "projectIdentity",
    phase: "identity",
    priority: 10,
    module: "./engines/projectIdentityEngine.js",
    exportName: "analyzeProjectIdentityBatch",
    dependsOn: [],
    inputContract: {
      requiredAny: [["address", "pairAddress", "symbol", "name"]],
      optional: ["chain", "url", "website", "twitterHandle", "githubRepo"],
    },
    outputContract: {
      requiredAny: [["projectIdentityVerdict", "identityResolutionScore", "projectIdentity"]],
      scoreFields: ["identityResolutionScore", "identityRiskScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "sourceTruth",
    phase: "evidence",
    priority: 20,
    module: "./engines/sourceTruthEngine.js",
    exportName: "analyzeSourceTruthBatch",
    dependsOn: ["projectIdentity"],
    inputContract: {
      requiredAny: [["source", "discoverySources", "sourceTruth", "evidence"]],
      optional: ["providerHealth", "evidenceQualityScore"],
    },
    outputContract: {
      requiredAny: [["sourceTruthScore", "sourceTruthVerdict", "sourceTruth"]],
      scoreFields: ["sourceTruthScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: false,
  },
  {
    id: "activeLiquidityTruth",
    phase: "liquidity",
    priority: 30,
    module: "./engines/activeLiquidityTruthEngine.js",
    exportName: "analyzeActiveLiquidityTruthBatch",
    dependsOn: ["projectIdentity"],
    inputContract: {
      requiredAny: [["liquidityUsd", "liquidity", "pairAddress"]],
      optional: ["volume24h", "hardExitLiquidityUsd"],
    },
    outputContract: {
      requiredAny: [["activeLiquidityTruthScore", "activeLiquidityTruthVerdict"]],
      scoreFields: ["activeLiquidityTruthScore", "liquidityControlRisk"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "organicBuyerClassifier",
    phase: "buyers",
    priority: 40,
    module: "./engines/organicBuyerClassifierEngine.js",
    exportName: "analyzeOrganicBuyerClassifierBatch",
    dependsOn: ["activeLiquidityTruth"],
    inputContract: {
      requiredAny: [["buyers24h", "buyTransactions24h", "organicBuyerScore", "holderGrowthScore"]],
      optional: ["walletClusters", "holderGrowthScore", "volume24h"],
    },
    outputContract: {
      requiredAny: [["organicBuyerScore", "organicBuyerVerdict"]],
      scoreFields: ["organicBuyerScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: false,
  },
  {
    id: "walletCluster",
    phase: "wallets",
    priority: 50,
    module: "./engines/walletClusterEngine.js",
    exportName: "analyzeWalletClusterBatch",
    dependsOn: ["projectIdentity"],
    inputContract: {
      requiredAny: [["wallets", "holders", "walletClusterRiskScore", "smartWalletScore"]],
      optional: ["buyers24h", "deployer", "ownerAddress"],
    },
    outputContract: {
      requiredAny: [["walletClusterScore", "walletClusterRiskScore", "walletClusterVerdict"]],
      scoreFields: ["walletClusterScore", "walletClusterRiskScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "instantSafetyGate",
    phase: "safety",
    priority: 60,
    module: "./engines/instantSafetyGateEngine.js",
    exportName: "analyzeInstantSafetyGateBatch",
    dependsOn: ["projectIdentity", "activeLiquidityTruth"],
    inputContract: {
      requiredAny: [["address", "contractVerified", "instantSafetyStatus", "riskScore"]],
      optional: ["ownerRenounced", "honeypot", "tax", "mintAuthority"],
    },
    outputContract: {
      requiredAny: [["instantSafetyStatus", "instantSafetyScore", "instantSafetyRiskScore"]],
      scoreFields: ["instantSafetyScore", "instantSafetyRiskScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "block-on-critical",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "organicDemandIntegrity",
    phase: "safety",
    priority: 70,
    module: "./engines/organicDemandIntegrityEngine.js",
    exportName: "analyzeOrganicDemandIntegrityBatch",
    dependsOn: ["activeLiquidityTruth", "organicBuyerClassifier", "walletCluster"],
    inputContract: {
      requiredAny: [["liquidityUsd", "volume24h", "organicBuyerScore", "organicDemandScore"]],
      optional: ["holders", "buyers24h", "sellPressureScore"],
    },
    outputContract: {
      requiredAny: [
        ["organicDemandVerdict", "organicEconomicIntegrityScore", "economicIntegrityRiskScore"],
      ],
      scoreFields: [
        "organicEconomicIntegrityScore",
        "economicIntegrityRiskScore",
        "activityAuthenticityRiskScore",
        "supplyIntegrityRiskScore",
      ],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "githubIntelligencePro",
    phase: "development",
    priority: 80,
    module: "./engines/githubIntelligenceProEngine.js",
    exportName: "analyzeGithubIntelligenceProBatch",
    dependsOn: ["projectIdentity"],
    inputContract: {
      requiredAny: [["githubRepo", "repository", "githubScore", "developerActivityScore"]],
      optional: ["githubStars", "githubCommits30d", "githubContributors"],
    },
    outputContract: {
      requiredAny: [["githubProScore", "githubProVerdict"]],
      scoreFields: ["githubProScore", "developerActivityScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: false,
  },
  {
    id: "roadmapCatalystProfit",
    phase: "catalyst",
    priority: 90,
    module: "./engines/roadmapCatalystProfitEngine.js",
    exportName: "analyzeRoadmapCatalystProfitBatch",
    dependsOn: ["sourceTruth"],
    inputContract: {
      requiredAny: [["roadmap", "description", "websiteText", "catalystScore", "liveCatalystEvents"]],
      optional: ["docsUrl", "milestones", "launchDate"],
    },
    outputContract: {
      requiredAny: [["roadmapProfitabilityScore", "roadmapCatalystVerdict", "roadmapMilestones"]],
      scoreFields: ["roadmapProfitabilityScore", "catalystScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: false,
    canBlockCandidate: false,
  },
  {
    id: "discoveryDecision",
    phase: "decision-precheck",
    priority: 100,
    module: "./engines/discoveryDecisionEngine.js",
    exportName: "analyzeDiscoveryDecisionBatch",
    dependsOn: ["projectIdentity", "instantSafetyGate", "organicDemandIntegrity"],
    inputContract: {
      requiredAny: [["discoveryPriorityScore", "nativeDiscoveryScore", "sourceTruthScore"]],
      optional: ["candidateLifecycleStage", "organicDemandFirewallStatus"],
    },
    outputContract: {
      requiredAny: [["discoveryDecisionScore", "discoveryDecisionTier"]],
      scoreFields: ["discoveryDecisionScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "sniperEvidenceFamily",
    phase: "proof",
    priority: 110,
    module: "./engines/sniperEvidenceFamilyEngine.js",
    exportName: "analyzeSniperEvidenceFamiliesBatch",
    dependsOn: ["sourceTruth", "activeLiquidityTruth", "githubIntelligencePro"],
    inputContract: {
      requiredAny: [["sourceTruthScore", "liquidityUsd", "githubProScore", "organicBuyerScore"]],
      optional: ["catalystScore", "smartWalletScore", "developerActivityScore"],
    },
    outputContract: {
      requiredAny: [["sniperEvidenceFamilySummary", "sniperEvidenceConfidence"]],
      scoreFields: ["sniperEvidenceConfidence"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: false,
  },
  {
    id: "sniperIntegrityGate",
    phase: "final-gate",
    priority: 120,
    module: "./engines/sniperIntegrityGateEngine.js",
    exportName: "analyzeSniperIntegrityGateBatch",
    dependsOn: ["sniperEvidenceFamily", "instantSafetyGate", "activeLiquidityTruth"],
    inputContract: {
      requiredAny: [["sniperEvidenceFamilySummary", "sniperEvidenceConfidence", "finalQualified"]],
      optional: ["purchaseRouteConfirmed", "tokenUnlockRiskScore"],
    },
    outputContract: {
      requiredAny: [["sniperState", "sniperIntegrityScore", "sniperIntegrityBlockers"]],
      scoreFields: ["sniperIntegrityScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "block-on-critical",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "proofOfAlphaExecutionTwin",
    phase: "execution",
    priority: 130,
    module: "./engines/proofOfAlphaExecutionTwinEngine.js",
    exportName: "analyzeProofOfAlphaExecutionTwinBatch",
    dependsOn: ["sniperIntegrityGate"],
    inputContract: {
      requiredAny: [["purchaseRouteConfirmed", "smallCapHunter", "liquidityUsd", "route"]],
      optional: ["slippagePct", "route", "preferredExchange"],
    },
    outputContract: {
      requiredAny: [["executionTwinVerdict", "executionTwinScore", "executionRoute"]],
      scoreFields: ["executionTwinScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: true,
  },
  {
    id: "alphaEvolutionGovernor",
    phase: "governor",
    priority: 140,
    module: "./engines/alphaEvolutionGovernorEngine.js",
    exportName: "analyzeAlphaEvolutionGovernorBatch",
    dependsOn: ["sourceTruth", "sniperIntegrityGate", "proofOfAlphaExecutionTwin"],
    inputContract: {
      requiredAny: [["alphaEvolutionGovernorScore", "pipelineScore", "institutionalScore"]],
      optional: ["alphaContractScore", "paperTradingOutcomeScore", "sourceTruthScore"],
    },
    outputContract: {
      requiredAny: [["alphaEvolutionGovernorScore", "alphaEvolutionGovernorVerdict"]],
      scoreFields: ["alphaEvolutionGovernorScore"],
      evidenceRequiredWhenScored: true,
    },
    timeoutMs: 7000,
    retries: 1,
    failureMode: "degrade",
    affectsFinalDecision: true,
    canBlockCandidate: false,
  },
];

export function getEngineContracts() {
  return [...ENGINE_CONTRACTS].sort((a, b) => a.priority - b.priority);
}

export function getContractsByPhase() {
  return getEngineContracts().reduce((acc, contract) => {
    acc[contract.phase] = acc[contract.phase] || [];
    acc[contract.phase].push(contract);
    return acc;
  }, {});
}

export function findEngineContract(id = "") {
  return getEngineContracts().find((contract) => contract.id === id) || null;
}
