import test from "node:test";
import assert from "node:assert/strict";

import {
  buildIntegrityStackReport,
} from "../src/reports/integrityStackReportEngine.js";
import { getEngineContracts } from "../src/kernel/engineContractManifest.js";

function provenProject(overrides = {}) {
  const contractAddress = "0x1111111111111111111111111111111111111111";
  const pairAddress = "0x2222222222222222222222222222222222222222";
  const quoteTimestamp = new Date().toISOString();
  const evidence = getEngineContracts().map((contract) => ({
    engine: contract.id,
    source: contract.id,
    family: contract.phase,
    signal: `${contract.id} evidence`,
    score: 84,
    confidence: 0.84,
  }));

  return {
    name: "Integrity Alpha",
    symbol: "INTA",
    chain: "base",
    address: contractAddress,
    tokenAddress: contractAddress,
    contractAddress,
    pairAddress,
    poolAddress: pairAddress,
    source: "native-discovery-mesh",
    dex: "Uniswap",
    discoverySources: ["native-discovery-mesh", "dexscreener", "github", "coingecko"],
    quoteTimestamp,
    projectIdentity: { score: 90, evidence: ["address", "github", "domain"] },
    projectIdentityVerdict: "Identity Resolved",
    identityResolutionScore: 90,
    identityRiskScore: 4,
    sourceTruthScore: 86,
    sourceTruthVerdict: "Verified Source Stack",
    sourceTruth: { sources: [{ source: "dexscreener" }, { source: "github" }, { source: "coingecko" }] },
    liquidityUsd: 900000,
    volume24h: 200000,
    priceUsd: 0.12,
    marketCap: 42_000_000,
    fdv: 52_000_000,
    circulatingMarketCapUsd: 42_000_000,
    activeLiquidityTruthScore: 84,
    organicBuyerScore: 80,
    buyerRetentionScore: 76,
    holderGrowthScore: 74,
    walletClusterScore: 78,
    walletClusterRiskScore: 8,
    smartWalletScore: 76,
    smartWalletArrivalScore: 74,
    smartMoneyAccumulationScore: 78,
    instantSafetyStatus: "PASS",
    instantSafetyScore: 92,
    instantSafetyRiskScore: 4,
    securityEvidenceSummary: {
      status: "EVIDENCE_AVAILABLE",
      providers: ["goplus", "sourcify-v2", "blockscout"],
      knownProviders: ["goplus", "sourcify-v2", "blockscout"],
      verifiedSource: true,
      malicious: false,
      honeypot: false,
      proxy: false,
      ownerRisk: false,
      mintRisk: false,
      freezeRisk: false,
      blacklistRisk: false,
      highTaxRisk: false,
      confidence: 86,
      riskFindings: [],
      warnings: [],
    },
    securityEvidence: [
      {
        provider: "goplus",
        status: "EVIDENCE_AVAILABLE",
        verifiedSource: true,
        riskFindings: [],
        warnings: [],
        confidence: 86,
      },
    ],
    contractAuthorityRiskScore: 6,
    contractAuthoritySafetyScore: 94,
    contractAuthorityVerdict: "CONTRACT_EVIDENCE_CLEAN",
    contractSafetyVerified: true,
    liquidityControlRiskScore: 8,
    liquidityControlRisk: 8,
    liquidityControlSafetyScore: 92,
    liquidityControlVerdict: "LIQUIDITY_CONTROL_ACCEPTABLE",
    liquidityControlEvidenceVerified: true,
    lpLockedPct: 82,
    lpBurnedPct: 0,
    ownerLpSharePct: 2,
    organicDemandFirewallStatus: "PASS",
    organicDemandFirewallScore: 86,
    organicDemandVerdict: "Organic Demand Confirmed",
    organicEconomicIntegrityScore: 84,
    economicIntegrityRiskScore: 8,
    githubRepo: "integrity/alpha",
    githubProScore: 78,
    developerActivityScore: 76,
    roadmap: "mainnet, native liquidity, integrations",
    roadmapProfitabilityScore: 76,
    roadmapCatalystVerdict: "bullish",
    roadmapMilestones: [{ title: "mainnet" }],
    catalystScore: 78,
    catalystCalendarScore: 74,
    narrativeScore: 77,
    narrativeForecastScore: 76,
    narrativeHeatScore: 73,
    nativeDiscoveryScore: 82,
    discoveryPriorityScore: 84,
    discoveryDecisionScore: 86,
    discoveryDecisionTier: "PASS",
    sniperEvidenceFamilySummary: { liquidity: { score: 82, evidence: ["usable liquidity"] } },
    sniperEvidenceConfidence: 86,
    sniperState: "ARMED",
    sniperQualified: true,
    sniperIntegrityScore: 88,
    sniperBlockingReasons: [],
    canonicalExecutionRoute: {
      status: "LIVE_EXECUTION_READY",
      routeTruthStatus: "LIVE_EXECUTION_READY",
      venue: "Uniswap",
      routeType: "DEX",
      chain: "base",
      contractAddress,
      pairAddress,
      quoteAsset: "USDC",
      routeUrl: `https://app.uniswap.org/swap?outputCurrency=${contractAddress}`,
      buyRouteAvailable: true,
      sellRouteAvailable: true,
      liquidityUsd: 900000,
      volume24hUsd: 200000,
      priceUsd: 0.12,
      quoteTimestamp,
      quoteAgeSeconds: 60,
      buyQuoteVerified: true,
      sellQuoteVerified: true,
      exactIdentityVerified: true,
      estimatedRoundTripSlippagePct: 0.028,
      supportingSources: ["dexscreener", "uniswap"],
      confidence: 92,
      missingEvidence: [],
      failureReasons: [],
    },
    canonicalExecutionRouteStatus: "LIVE_EXECUTION_READY",
    canonicalExecutionRouteConfidence: 92,
    executionProof: {
      executionStatus: "LIVE_EXECUTION_READY",
      executionProofState: "LIVE_EXECUTION_READY",
      routeTruthStatus: "LIVE_EXECUTION_READY",
      chainId: "base",
      contractAddress,
      venue: "Uniswap",
      pairAddress,
      quoteAsset: "USDC",
      price: 0.12,
      liquidityUsd: 900000,
      volume24hUsd: 200000,
      buyRouteAvailable: true,
      sellRouteAvailable: true,
      buyQuoteVerified: true,
      sellQuoteVerified: true,
      exactIdentityVerified: true,
      observedSlippagePct: 0.028,
      quoteTimestamp,
      quoteAgeSeconds: 60,
      orderBookDepthVerified: true,
      orderBookDepthUsd: 900000,
      chainVerified: true,
      contractVerified: true,
      poolVerified: true,
      quoteVerified: true,
      safetyVerified: true,
      failureReasons: [],
    },
    routeTruthStatus: "LIVE_EXECUTION_READY",
    executionProofState: "LIVE_EXECUTION_READY",
    executionStatus: "LIVE_EXECUTION_READY",
    exactIdentityVerified: true,
    buyQuoteVerified: true,
    sellQuoteVerified: true,
    orderBookDepthVerified: true,
    orderBookDepthUsd: 900000,
    estimatedRoundTripSlippagePct: 0.028,
    quoteAgeSeconds: 60,
    moneyStatus: "VERIFIED",
    moneyScore: 84,
    moneyConfidence: 86,
    moneyEvidence: {
      buyRoute: { value: true, status: "VERIFIED" },
      sellRoute: { value: true, status: "VERIFIED" },
      contract: { value: contractAddress, status: "VERIFIED" },
      pool: { value: pairAddress, status: "VERIFIED" },
    },
    purchaseRouteConfirmed: true,
    smallCapHunterScore: 82,
    smallCapExecutionScore: 82,
    smallCapRiskScore: 6,
    smallCapHunterVerdict: "Top-2 Small-Cap Research Candidate",
    smallCapHunter: {
      score: 82,
      verdict: "Top-2 Small-Cap Research Candidate",
      routeStatus: "VERIFIED",
      missingEvidence: [],
      blockers: [],
      executionReady: true,
      researchOnly: false,
      purchaseRoute: {
        status: "VERIFIED",
        purchasable: true,
        preferredRoute: "Uniswap",
        score: 92,
        buyRouteAvailable: true,
        sellRouteAvailable: true,
        routeType: "DEX",
        chain: "base",
        contract: contractAddress,
        pairAddress,
      },
    },
    executionTwinVerdict: "Route Verified",
    executionTwinScore: 84,
    alphaEvolutionGovernorScore: 86,
    alphaEvolutionGovernorVerdict: "Governor Promote",
    proofOfAlphaExecutionTwinScore: 84,
    proofOfAlphaExecutionTwinVerdict: "Execution-Verified Alpha Candidate",
    proofOfAlphaExecutionTwinRoute: "Uniswap",
    proofOfAlphaExecutionTwin: {
      score: 84,
      verdict: "Execution-Verified Alpha Candidate",
      confidence: "High",
      route: {
        detected: true,
        preferredRoute: "Uniswap",
        status: "VERIFIED",
        confidence: 88,
      },
      quote: {
        liquidityUsd: 900000,
        volume24h: 200000,
        priceUsd: 0.12,
        estimatedSlippagePct: 0.028,
      },
      safety: {
        blockers: [],
        contractKnown: true,
        pairKnown: true,
      },
    },
    opportunityTimingScore: 86,
    opportunityTimingLevel: "favorable timing",
    opportunityTimingComponents: {
      notAlreadyPumped: 84,
      liquidityBeforePrice: 86,
      buyersBeforeRetail: 82,
    },
    attentionGapScore: 80,
    attentionGapLevel: "strong attention gap",
    attentionGapComponents: {
      developerVsPrice: 82,
      liquidityVsSocial: 80,
      catalystVsCoverage: 78,
    },
    progressiveOpportunityScore: 88,
    trustScore: 86,
    executionScore: 82,
    moneyRankScore: 85,
    moneyRankEligible: true,
    marketOpportunityRank: 86,
    localAIConsensusScore: 84,
    recommendedHorizon: "7_14_DAYS",
    marketOpportunityLearningScore: 68,
    marketOpportunityLearningConfidence: "LOW_SAMPLE",
    learnedMarketOpportunityRank: 87,
    sevenDayTenXScore: 82,
    sevenDayTenXRawScore: 84,
    sevenDayTenXPenaltyTotal: 2,
    sevenDayTenXVerdict: "Qualified 7-Day Asymmetric Research Candidate",
    sevenDayTenXConfidence: "Medium",
    sevenDayTenXSelectedEligible: true,
    sevenDayTenXModeledScenarioPct: 9.4,
    sevenDayTenXMarketCap: 4_500_000,
    sevenDayTenXLiquidityUsd: 900_000,
    sevenDayTenXBlockers: [],
    sevenDayTenXMissingEvidence: [],
    sevenDayTenX: {
      score: 82,
      verdict: "Qualified 7-Day Asymmetric Research Candidate",
      components: {
        lowCapLeverage: 94,
        sevenDayMomentum: 82,
        nearTermCatalyst: 78,
        organicDemand: 80,
        smartMoneyArrival: 76,
        liquidityTradability: 86,
        evidenceTrust: 84,
        safetyIntegrity: 90,
      },
      blockers: [],
      missingEvidence: [],
    },
    scalpMicrostructureScore: 86,
    scalpMicrostructureLane: "SCALP_ACTIONABLE_RESEARCH",
    scalpResearchQualified: true,
    scalpNoTrade: false,
    scalpEstimatedTotalCostPct: 1.4,
    scalpTradeSizeUsd: 100,
    scalpLiquidityUsd: 900000,
    scalpDepthUsd: 900000,
    scalpTradeSizeToDepthPct: 0.01,
    scalpQuoteAgeSeconds: 60,
    scalpMicrostructureBlockers: [],
    scalpMicrostructureWarnings: [],
    scalpMicrostructure: {
      name: "Scalp Microstructure Engine",
      lane: "SCALP_ACTIONABLE_RESEARCH",
      score: 86,
      tradeSizeUsd: 100,
      liquidityUsd: 900000,
      depthUsd: 900000,
      buyRouteAvailable: true,
      sellRouteAvailable: true,
      quoteAgeSeconds: 60,
      routeCost: { totalCostPct: 1.4, spreadPct: 0.3, roundTripSlippagePct: 0.9, routeFeePct: 0.2 },
      componentScores: { routeScore: 100, depthScore: 100, costScore: 88, extensionScore: 94 },
      blockers: [],
      warnings: [],
    },
    routeAccessibility: {
      globalRouteQualityScore: 92,
      userAccessibilityScore: 88,
      routeTruthStatus: "LIVE_EXECUTION_READY",
      buyQuoteVerified: true,
      sellQuoteVerified: true,
      regionStatus: "CONFIRMED_AVAILABLE",
    },
    globalRouteQualityScore: 92,
    userAccessibilityScore: 88,
    executionReady: true,
    userAccessible: true,
    utilityQualityScore: 84,
    realUtilityScore: 84,
    utilityClassification: "REAL_UTILITY",
    realUtilityQualified: true,
    preBreakoutRadarScore: 86,
    preBreakoutRadarLane: "ARMED",
    preBreakoutRadar: {
      score: 86,
      lane: "ARMED",
      verdict: "Pre-breakout research setup",
    },
    highUpsideScalpScore: 84,
    highUpsideScalpLane: "SCALP_READY_RESEARCH",
    highUpsideScalpDataCoverage: 88,
    dailyCapitalMoveScore: 83,
    dailyCapitalMoveLane: "CAPITAL_MOVE_RESEARCH",
    dailyCapitalMoveReason: "Highest evidence-backed candidate for manual capital-move research.",
    dailyCapitalMoveMissingProof: [],
    dailyCapitalMoveMissingProofCount: 0,
    dailyCapitalMoveNextSources: [],
    dailyCapitalMoveConfidence: "HIGH",
    dailyCapitalMoveExecutionReady: true,
    dailyCapitalMoveExecutionTruthState: "LIVE_EXECUTION_READY",
    dailyCapitalMoveSafetyStatus: "NO_DETERMINISTIC_BLOCK",
    timeHorizonScores: {
      "24_72_HOURS": 80,
      "7_14_DAYS": 86,
      "30_90_DAYS": 82,
    },
    opportunityEvidenceRecord: {
      projectKey: `base:${contractAddress}`,
      scores: { marketOpportunityRank: 86 },
      evidenceFamilies: [{ family: "liquidity", score: 82 }],
    },
    opportunityEvidenceCoverage: 90,
    opportunityRankingTier: "SNIPER_READY",
    bestAvailableEligible: true,
    missingEvidence: [],
    pipelineScore: 88,
    institutionalScore: 86,
    finalQualified: true,
    finalState: "PROMOTED",
    finalSelectionQualified: true,
    finalSelectionState: "QUALIFIED",
    finalContractAddress: contractAddress,
    calibrationScore: 72,
    outcomeLearningScore: 70,
    riskScore: 6,
    trapRiskScore: 4,
    sellPressureScore: 16,
    evidence,
    ...overrides,
  };
}

function metaFixture() {
  return {
    discovery: {
      universeLedger: {
        savedProjects: 1,
        totals: {
          promoted: 1,
          researchOnly: 0,
          blocked: 0,
          targetMet: false,
          targetShortfall: 38999,
        },
      },
      sourceReports: {
        nativeDiscoveryMesh: {
          status: "SUCCESS",
          enabled: true,
          scannedTokens: 1,
        },
        dexscreener: {
          status: "SUCCESS",
          scannedTokens: 1,
        },
      },
    },
  };
}

test("integrity stack verifies the core institutional safety layers", () => {
  const report = buildIntegrityStackReport([provenProject()], metaFixture());
  const componentIds = report.components.map((component) => component.id);

  assert.equal(report.status, "PASS");
  assert.ok(report.readinessScore >= 90);
  assert.deepEqual(
    [
      "final-selection-integrity",
      "sniper-integrity-gate",
      "evidence-calibrated-kernel",
      "advanced-brain-kernel",
      "universe-ledger",
      "native-discovery-mesh",
      "provider-failure-tests",
      "symbol-collision-protection",
      "report-consistency-tests",
    ].every((id) => componentIds.includes(id)),
    true
  );
});

test("integrity stack catches unprotected report and selection contradictions", () => {
  const report = buildIntegrityStackReport(
    [
      provenProject({
        symbol: "BAD",
        finalSelectionState: "BLOCKED",
        finalSelectionQualified: true,
        aiDecision: "Reject",
      }),
    ],
    metaFixture()
  );

  assert.equal(report.status, "FAIL");
  assert.ok(report.components.some((component) => component.id === "final-selection-integrity" && component.status === "FAIL"));
  assert.ok(report.components.some((component) => component.id === "report-consistency-tests" && component.status === "FAIL"));
});

test("integrity stack reports symbol collision protection", () => {
  const report = buildIntegrityStackReport(
    [
      provenProject({ symbol: "SAME", chain: "base", address: "0xsamebase" }),
      provenProject({ symbol: "SAME", chain: "ethereum", address: "0xsameeth" }),
    ],
    metaFixture()
  );
  const component = report.components.find((item) => item.id === "symbol-collision-protection");

  assert.equal(component.status, "PASS");
  assert.equal(component.metrics.collisionSymbols, 1);
  assert.equal(component.metrics.protectedCollisions, 1);
});
