import test from "node:test";
import assert from "node:assert/strict";
import { buildCausalMarketWorldModel, strongestPaths } from "../src/production/causalMarketWorldModel.js";
import { simulateCounterfactualMarket, defaultCounterfactualScenarios } from "../src/production/counterfactualMarketSimulator.js";
import { analyzeAdversarialMarketIntelligence } from "../src/production/adversarialMarketIntelligence.js";
import { detectMarketShockEarlyWarning } from "../src/production/marketShockEarlyWarning.js";
import { buildOpportunityDependencyGraph } from "../src/production/opportunityDependencyGraph.js";
import { detectEarliestSeparatingCause } from "../src/production/earliestCauseDetector.js";
import { evaluateLeadTimeModel } from "../src/production/leadTimeOptimization.js";
import { buildEdgeFrontier } from "../src/production/edgeFrontier.js";
import { accountEvidenceValue } from "../src/production/evidenceValueAccounting.js";
import { buildPredictiveMarketDiscoveryNetwork } from "../src/production/predictiveMarketDiscoveryNetwork.js";
import { buildMarketDiscoveryEngine } from "../src/production/marketDiscoveryEngine.js";

const token="0x"+"1".repeat(40);
function candidate(overrides={}){return{identityKey:`base:${token}`,chain:"base",tokenAddress:token,symbol:"EDGE",liquidityUsd:800000,marketCapUsd:12000000,capitalMigrationScore:80,regimeCompatibilityScore:82,walletEntityScore:75,walletEntityIds:["entity:a"],narratives:["ai"],narrativePropagationScore:70,sellerExhaustionScore:72,liquidityConvexityIndex:70,probability50Pct:45,failureProbabilityPct:15,executionAwareEV:{captureableExpectedValuePct:18,routeQuality:.9},opportunityHalfLife:{remainingAsymmetryPct:80},governor:{alphaOSScore:84},...overrides};}

test("world model excludes future explicit events",()=>{const p=candidate();const model=buildCausalMarketWorldModel({projects:[p],regime:{state:"RISK_ON",confidence:80},events:[{from:"A",to:"B",observedAt:"2026-01-03T00:00:00Z"}]},{asOf:"2026-01-02T00:00:00Z"});assert.equal(model.summary.observedEvents,0);assert.equal(model.policy.causalClaimAllowed,false);});
test("world model produces upstream paths",()=>{const p=candidate();const model=buildCausalMarketWorldModel({projects:[p],regime:{state:"RISK_ON",confidence:80}},{asOf:"2026-01-02T00:00:00Z"});const paths=strongestPaths(model,`PROJECT:${p.identityKey}`);assert.ok(paths.length>0);});
test("counterfactual scenarios are deterministic and non-causal",()=>{const a=simulateCounterfactualMarket(candidate(),defaultCounterfactualScenarios(),{seed:9});const b=simulateCounterfactualMarket(candidate(),defaultCounterfactualScenarios(),{seed:9});assert.deepEqual(a,b);assert.equal(a.policy.causalForecastClaimAllowed,false);});
test("adversarial intelligence compresses sybil-looking wallets",()=>{const r=analyzeAdversarialMarketIntelligence(candidate({walletTemporalFingerprint:{walletCount:20},walletEntityIds:["e1","e2"],walletTemporalRiskScore:70}),{walletEntities:{entities:[{entityId:"e1",walletCount:10},{entityId:"e2",walletCount:10}]}});assert.ok(r.riskScore>0);assert.equal(r.policy.accusationOfFraud,false);});
test("market shock warning uses only observations before as-of",()=>{const rows=[0,1,2,3].map(i=>({observedAt:`2026-01-01T0${i}:00:00Z`,btcReturn24hPct:-i,altBreadthPct:70-i*10,marketVolatilityPercentile:40+i*15,stablecoinLiquidityChangePct:-i,dexVolumeChangePct:-i*5}));rows.push({observedAt:"2026-01-02T00:00:00Z",btcReturn24hPct:-99});const r=detectMarketShockEarlyWarning(rows,{asOf:"2026-01-01T04:00:00Z"});assert.equal(r.observations,4);});
test("dependency graph blocks broken critical dependency",()=>{const r=buildOpportunityDependencyGraph(candidate({capitalMigrationScore:20}));assert.equal(r.state,"EDGE_DEPENDENCY_BROKEN");});
test("earliest cause excludes post-breakout rows",()=>{const winner=[{observedAt:"2026-01-01T01:00:00Z",features:{x:100}},{observedAt:"2026-01-02T02:00:00Z",features:{future:999}}];const controls=[[{observedAt:"2026-01-01T01:00:00Z",features:{x:10}}],[{observedAt:"2026-01-01T01:00:00Z",features:{x:12}}],[{observedAt:"2026-01-01T01:00:00Z",features:{x:9}}]];const r=detectEarliestSeparatingCause(winner,controls,{breakoutAt:"2026-01-02T00:00:00Z",minimumControls:3});assert.equal(r.candidates.some(x=>x.feature==="future"),false);});
test("lead time optimizer rewards useful advance warning",()=>{const rows=Array.from({length:60},(_,i)=>({hit:i<40,leadTimeHours:i<40?6:null,realizedReturnPct:i<40?30:-5}));const r=evaluateLeadTimeModel(rows,{minimumSamples:50});assert.equal(r.samples,60);assert.ok(r.alphaLeadTimeScore>0);});
test("edge frontier removes strictly dominated candidate",()=>{const a=candidate({identityKey:"a",executionAwareEV:{captureableExpectedValuePct:30},governor:{alphaOSScore:90},opportunityHalfLife:{remainingAsymmetryPct:90},capitalMigrationScore:90});const b=candidate({identityKey:"b",executionAwareEV:{captureableExpectedValuePct:10},governor:{alphaOSScore:60},opportunityHalfLife:{remainingAsymmetryPct:40},capitalMigrationScore:50});const f=buildEdgeFrontier([a,b]);assert.equal(f.frontier.some(x=>x.identityKey==="a"),true);assert.equal(f.frontier.some(x=>x.identityKey==="b"),false);});
test("evidence accounting ranks useful sources",()=>{const r=accountEvidenceValue([{source:"wallet",winnerRescued:true,costUnits:1},{source:"social",costUnits:10}]);assert.equal(r.sources[0].source,"wallet");});
test("predictive discovery matches future shape without promising returns",()=>{const hist=Array.from({length:50},(_,i)=>({chain:"base",narratives:["ai"],marketCapUsd:5e6,liquidityUsd:500000,leadTimeHours:4}));const r=buildPredictiveMarketDiscoveryNetwork({historicalWinners:hist,candidates:[candidate({marketCapUsd:5e6,liquidityUsd:500000})]});assert.equal(r.forecast.chain,"base");assert.equal(r.policy.notPriceGuarantee,true);});
test("CLI 8 orchestrator stays research-only",()=>{const p=candidate();const r=buildMarketDiscoveryEngine({candidates:[p],regime:{state:"RISK_ON",confidence:80},historicalWinners:Array.from({length:45},()=>({chain:"base",narratives:["ai"],marketCapUsd:5e6,liquidityUsd:500000,leadTimeHours:3}))},{now:"2026-01-02T00:00:00Z"});assert.equal(r.system,"CLI_8_MARKET_DISCOVERY_ENGINE");assert.equal(r.policy.automaticTrading,false);assert.equal(r.policy.worldModelCausalClaimAllowed,false);});
