import { clamp, finite, mean, timestamp } from "./productionMath.js";
const METRICS=["btcReturn24hPct","ethReturn24hPct","altBreadthPct","dexVolumeChangePct","stablecoinLiquidityChangePct","marketVolatilityPercentile","newPoolFormationChangePct"];
function slope(rows,key){const active=rows.map(r=>({t:timestamp(r.observedAt||r.generatedAt||r.timestamp),v:finite(r[key])})).filter(r=>r.t!==null&&r.v!==null).sort((a,b)=>a.t-b.t); if(active.length<2)return null; const t0=active[0].t; const xs=active.map(r=>(r.t-t0)/3600000), ys=active.map(r=>r.v); const mx=mean(xs),my=mean(ys); const den=xs.reduce((s,x)=>s+(x-mx)**2,0); return den?xs.reduce((s,x,i)=>s+(x-mx)*(ys[i]-my),0)/den:null;}
export function detectMarketShockEarlyWarning(history = [], options = {}) {
  const asOf=options.asOf || new Date().toISOString(), asOfMs=timestamp(asOf); const lookbackHours=Math.max(1,Number(options.lookbackHours||12)); const rows=(Array.isArray(history)?history:[]).filter(r=>{const t=timestamp(r.observedAt||r.generatedAt||r.timestamp);return t!==null&&t<=asOfMs&&t>=asOfMs-lookbackHours*3600000;}).sort((a,b)=>timestamp(a.observedAt||a.generatedAt||a.timestamp)-timestamp(b.observedAt||b.generatedAt||b.timestamp));
  const slopes=Object.fromEntries(METRICS.map(k=>[k,slope(rows,k)])); const stressSignals=[clamp(Math.max(0,-(slopes.btcReturn24hPct||0))/2),clamp(Math.max(0,-(slopes.altBreadthPct||0))/8),clamp(Math.max(0,(slopes.marketVolatilityPercentile||0))/8),clamp(Math.max(0,-(slopes.stablecoinLiquidityChangePct||0))/3),clamp(Math.max(0,-(slopes.dexVolumeChangePct||0))/8)]; const score=(mean(stressSignals)||0)*100;
  const state=rows.length<3?"INSUFFICIENT_MARKET_HISTORY":score>=70?"SHOCK_TRANSITION_LIKELY":score>=45?"STRESS_ACCELERATING":score>=25?"REGIME_TRANSITION_WATCH":"STABLE";
  return { generatedAt:asOf,state,warningScore:Number(score.toFixed(2)),observations:rows.length,slopes,policy:{earlyWarningOnly:true,notOfficialRegimeClassifier:true,futureEvidenceAllowed:false} };
}
