import { robustZScore } from "../math/robustStatistics.js";
import { appendCanonicalThreeClockObservations, historyForCanonicalThreeClock, loadCanonicalThreeClockObservations } from "../data/canonicalThreeClockObservationStore.js";

const HISTORY_REQUIRED = 5;
const numberOrNull = (value) => { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : null; };
const clamp = (value) => Math.max(0, Math.min(100, numberOrNull(value) ?? 0));
function get(project, paths) { for (const path of paths) { const value = path.split(".").reduce((obj, key) => obj?.[key], project); if (value !== undefined && value !== null && value !== "") return numberOrNull(value); } return null; }
function weighted(items) { const active = items.filter(([value]) => value !== null); return active.length ? active.reduce((sum, [value, weight]) => sum + value * weight, 0) / active.reduce((sum, [, weight]) => sum + weight, 0) : null; }
function amountScore(value) { return value === null || value < 0 ? null : clamp(Math.log10(value + 1) / 6 * 100); }
function historyScores(history, clock) { return history.map((row) => numberOrNull(row?.[`${clock}Clock`]?.score)).filter((value) => value !== null); }
function clock(clock, score, evidence, history) { const historical = historyScores(history, clock); const surprise = robustZScore(score, historical, { minSample: HISTORY_REQUIRED }); return { score: score === null ? null : Math.round(clamp(score)), robustSurprise: surprise === null ? null : Number(surprise.toFixed(3)), accelerating: surprise !== null && surprise >= 1, history: { observations: historical.length, required: HISTORY_REQUIRED, sufficient: historical.length >= HISTORY_REQUIRED }, confidence: Math.round(Object.values(evidence).filter((value) => value !== null).length / Object.keys(evidence).length * 100), evidence }; }
function blocked(project) { return project.honeypotDetected === true || project.verifiedScam === true || project.sellRestricted === true || project.identityConflict === true || project.canonicalIdentityHardBlock === true || project.instantSafetyStatus === "CRITICAL" || Number(project.washTradingRiskScore) >= 85; }
function topography(project) { const bands = project.liquidityBands || project.liquidityTopography?.bands; const price = get(project, ["priceUsd", "price"]); if (!Array.isArray(bands) || price === null || price <= 0) return { mode: "UNOBSERVED", upsideVacuumScore: null }; const valid = bands.map((band) => ({ low: numberOrNull(band.lowerPrice ?? band.priceLow), high: numberOrNull(band.upperPrice ?? band.priceHigh), liquidity: numberOrNull(band.liquidityUsd ?? band.depthUsd) })).filter((band) => band.low !== null && band.high !== null && band.high > band.low && band.liquidity !== null); if (!valid.length) return { mode: "UNOBSERVED", upsideVacuumScore: null }; const depth = (low, high) => valid.reduce((sum, band) => sum + Math.max(0, Math.min(high, band.high) - Math.max(low, band.low)) / (band.high - band.low) * band.liquidity, 0); const near = depth(price, price * 1.05), next = depth(price * 1.05, price * 1.2); return { mode: "EXPLICIT_RANGE_TOPOGRAPHY", upsideVacuumScore: Math.round(clamp((1 - next / Math.max(near, 1)) * 100)), upsideDepth0To5PctUsd: Math.round(near), upsideDepth5To20PctUsd: Math.round(next) }; }
function compression(project, history) { const timestamps = project.ignitionTwin?.eventTimeAcceleration?.eventTimestamps || project.ignitionRawSensors?.eventTimestamps || project.eventTimestamps; if (Array.isArray(timestamps) && timestamps.length >= 6) { const times = timestamps.map((timestamp) => new Date(timestamp).getTime()).filter(Number.isFinite).sort((a, b) => a - b); const intervals = times.slice(1).map((time, index) => time - times[index]).filter((value) => value > 0); if (intervals.length >= 5) { const baseline = intervals.slice(0, -3).sort((a, b) => a - b)[Math.floor((intervals.length - 3) / 2)]; const recent = intervals.slice(-3).sort((a, b) => a - b)[1]; const ratio = baseline && recent ? baseline / recent : null; return { state: ratio === null ? "UNOBSERVED" : ratio >= 1.4 ? "COMPRESSING" : ratio <= .7 ? "DECELERATING" : "STABLE", ratio, source: "OBSERVED_EVENT_TIMESTAMPS" }; } } const prior = history.map((row) => row.sequence?.state).filter(Boolean); return { state: prior.length >= 3 ? "SEQUENCE_HISTORY_PRESENT_BUT_EVENT_TIME_UNOBSERVED" : "UNOBSERVED", ratio: null, source: "NO_OBSERVED_EVENT_TIMESTAMPS" }; }

export function analyzeCanonicalThreeClockEdge(project = {}, options = {}) {
  const history = Array.isArray(options.history) ? options.history : [];
  const projectEvidence = { developer: get(project, ["developerAccelerationScore", "developerActivityScore", "developerScore"]), change: get(project, ["projectChangeScore"]), repository: get(project, ["githubProScore", "githubQualityScore"]), catalyst: get(project, ["liveCatalystRadarScore", "catalystCalendarScore"]), adoption: get(project, ["adoptionAccelerationScore", "ecosystemIntegrationScore"]) };
  const p = clock("project", weighted([[projectEvidence.developer, 1.4], [projectEvidence.change, 1.25], [projectEvidence.repository, .7], [projectEvidence.catalyst, .8], [projectEvidence.adoption, .9]]), projectEvidence, history);
  const capital = { observedDeployedCapitalUsd: get(project, ["observedDeployedCapitalUsd", "capitalFlowBaseline.netFlowUsd", "capitalFlowObservation.netFlowUsd", "netFlowUsd"]), explicitTargetProximityCapitalUsd: get(project, ["explicitTargetProximityCapitalUsd", "targetProximityCapitalUsd"]), stagedCommittedCapitalUsd: get(project, ["stagedCommittedCapitalUsd", "committedCapitalUsd"]), probabilityWeightedInferredCapitalUsd: get(project, ["probabilityWeightedInferredCapitalUsd", "inferredCapitalUsd"]) };
  const capitalEvidence = { observed: amountScore(capital.observedDeployedCapitalUsd), proximity: amountScore(capital.explicitTargetProximityCapitalUsd), committed: amountScore(capital.stagedCommittedCapitalUsd), inferred: amountScore(capital.probabilityWeightedInferredCapitalUsd), migration: get(project, ["capitalMigrationCoreScore", "capitalMigrationScore"]), flow: get(project, ["capitalFlowScore"]), wallets: get(project, ["smartWalletArrivalScore", "smartMoneyAccumulationScore"]), breadth: get(project, ["buyerBreadthAccelerationScore"]) };
  const c = { ...clock("capital", weighted([[capitalEvidence.observed, 1.3], [capitalEvidence.proximity, 1], [capitalEvidence.committed, .8], [capitalEvidence.inferred, .3], [capitalEvidence.migration, 1], [capitalEvidence.flow, 1], [capitalEvidence.wallets, 1], [capitalEvidence.breadth, .8]]), capitalEvidence, history), capital, evidenceMode: capital.observedDeployedCapitalUsd !== null ? "OBSERVED_DEPLOYED_CAPITAL" : capital.explicitTargetProximityCapitalUsd !== null || capital.stagedCommittedCapitalUsd !== null ? "EXPLICIT_PREPARATION" : "DERIVED_SUPPORT_ONLY" };
  const oneDay = get(project, ["priceChange24hPct", "priceChange24h"]), sevenDay = get(project, ["priceChange7dPct", "priceChange7d"]); const extension = oneDay === null && sevenDay === null ? null : clamp(Math.max(Math.max(0, oneDay || 0) * 1.4, Math.max(0, sevenDay || 0) * .65));
  const attentionEvidence = { social: get(project, ["socialAccelerationScore"]), x: get(project, ["xSocialScore"]), narrative: get(project, ["narrativeHeatScore"]), holders: get(project, ["holderGrowthScore"]), volume: get(project, ["volumeAccelerationScore"]), media: get(project, ["newsCoverageScore", "externalSignalScore"]), priceExtension: extension };
  const a = { ...clock("attention", weighted([[attentionEvidence.social, 1.2], [attentionEvidence.x, .8], [attentionEvidence.narrative, 1], [attentionEvidence.holders, .65], [attentionEvidence.volume, .8], [attentionEvidence.media, .65], [attentionEvidence.priceExtension, 1.25]]), attentionEvidence, history), quietScore: extension === null ? null : 100 - clamp(weighted([[attentionEvidence.social, 1.2], [attentionEvidence.x, .8], [attentionEvidence.narrative, 1], [attentionEvidence.holders, .65], [attentionEvidence.volume, .8], [attentionEvidence.media, .65], [attentionEvidence.priceExtension, 1.25]])), priceExtension: extension === null ? "UNKNOWN" : extension >= 75 ? "MATERIALLY_EXTENDED" : extension >= 40 ? "EXTENDING" : "NOT_EXTENDED" };
  const enoughHistory = p.history.sufficient && c.history.sufficient && a.history.sufficient, unsafe = blocked(project), priceExtended = a.priceExtension === "MATERIALLY_EXTENDED";
  const projectHigh = p.score !== null && p.score >= 65, capitalHigh = c.score !== null && c.score >= 58, attentionQuiet = a.score !== null && a.score <= 42, attentionCaughtUp = a.score !== null && a.score >= 58;
  const qualifying = !unsafe && enoughHistory && p.accelerating && c.accelerating && projectHigh && capitalHigh && attentionQuiet && !priceExtended;
  const sequence = unsafe ? { state: "SEQUENCE_BROKEN", reason: "SAFETY_BLOCKED", qualifying: false } : !enoughHistory ? { state: "INSUFFICIENT_HISTORY", qualifying: false } : a.score === null || a.priceExtension === "UNKNOWN" ? { state: "SEQUENCE_BROKEN", reason: "ATTENTION_OR_PRICE_UNKNOWN", qualifying: false } : priceExtended ? { state: "PRICE_BREAKOUT", qualifying: false } : qualifying ? { state: "THREE_CLOCK_PRE_CONSENSUS", qualifying: true } : p.accelerating && !c.accelerating ? { state: "PROJECT_LEADS", qualifying: false } : projectHigh && capitalHigh && attentionCaughtUp ? { state: "ATTENTION_CATCHING_UP", qualifying: false } : projectHigh && capitalHigh ? { state: "PROJECT_PLUS_CAPITAL", qualifying: false } : { state: "NO_SEQUENCE", qualifying: false };
  const priorQualifier = history.find((row) => row.qualifying); const hours = priorQualifier ? Math.max(0, (Date.now() - Date.parse(priorQualifier.observedAt)) / 3_600_000) : 0; const freshness = !qualifying && priorQualifier ? { state: priceExtended || (a.score || 0) >= 58 ? "EXPIRED" : "DECAYING", firstQualifiedAt: priorQualifier.observedAt } : { state: qualifying ? "FRESH" : "NOT_STARTED", firstQualifiedAt: priorQualifier?.observedAt || null, elapsedHours: Number(hours.toFixed(2)) };
  const topo = topography(project); const liquidity = get(project, ["stableExitLiquidityUsd", "dexLiquidityUsd", "liquidityUsd", "liquidity"]); const pressureTwin = { mode: liquidity === null ? "UNAVAILABLE" : topo.mode === "EXPLICIT_RANGE_TOPOGRAPHY" ? "RANGE_AWARE_CONSTANT_PRODUCT_HEURISTIC" : "CONSTANT_PRODUCT_HEURISTIC", executableQuote: false, shadowOnly: true, warning: "Heuristic only; no executable quote is implied." };
  const edge = { version: "three-clock-canonical-v2", shadowOnly: true, rankingInfluence: false, projectClock: p, capitalClock: c, attentionClock: a, sequence, sequenceCompression: compression(project, history), freshness, liquidityTopography: topo, asymmetricPressureTwin: pressureTwin, ignitionContext: { capitalMigrationScore: get(project, ["capitalMigrationCoreScore", "capitalMigrationScore"]), ignitionState: project.ignitionState || "UNKNOWN", integrationMode: "CONTEXT_ONLY" }, qualifying, provenance: { observedAt: options.observedAt || new Date().toISOString(), capitalAccounting: "Observed, target-proximity, committed, and inferred capital are never combined." } };
  return { ...project, canonicalThreeClockEdge: edge, threeClockEdge: edge, threeClockEdgeScore: 0, threeClockRankingInfluence: false, threeClockSequenceState: sequence.state, threeClockQualifying: qualifying, projectClockScore: p.score, capitalClockScore: c.score, attentionClockScore: a.score, liquidityTopographyMode: topo.mode };
}

export function analyzeCanonicalThreeClockBatch(projects = [], options = {}) { const rows = options.observations || loadCanonicalThreeClockObservations(options.store || {}); const analyzed = (Array.isArray(projects) ? projects : []).map((project) => analyzeCanonicalThreeClockEdge(project, { ...options, history: historyForCanonicalThreeClock(project, rows, options.history || {}) })); if (options.persist === true) appendCanonicalThreeClockObservations(analyzed, { ...(options.store || {}), observedAt: options.observedAt }); return analyzed; }
export function summarizeCanonicalThreeClock(projects = []) { const rows = projects.filter((project) => project.canonicalThreeClockEdge); return { generatedAt: new Date().toISOString(), status: "SHADOW_ONLY", rankingInfluence: false, analyzed: rows.length, qualifying: rows.filter((row) => row.threeClockQualifying).length, stateCounts: rows.reduce((counts, row) => { counts[row.threeClockSequenceState] = (counts[row.threeClockSequenceState] || 0) + 1; return counts; }, {}) }; }
