import fs from "fs";
import path from "path";

function clean(value = "") {
  return String(value ?? "")
    .replace(/"/g, '""')
    .replace(/\n/g, " ")
    .trim();
}

export function writeCsvReport(projects = []) {
  const reportsDir = path.resolve("reports");
  fs.mkdirSync(reportsDir, { recursive: true });

  const headers = [
    "rank",
    "name",
    "symbol",
    "chain",
    "finalSelectionState",
    "finalSelectionQualified",
    "finalIntegrityScore",
    "finalIntegrityVerdict",
    "finalBlockingReasons",
    "finalWarningReasons",
    "finalIdentityState",
    "permanentProjectKey",
    "purchaseRouteConfirmed",
    "executionRouteAvailable",
    "liquidityVerified",
    "preConsensusRank",
    "preConsensusCandidateType",
    "preConsensusTier",
    "preConsensusOpportunityScore",
    "regimeAdjustedOpportunityScore",
    "informationAdvantageScore",
    "estimatedConsensusStage",
    "quietAccumulationDetected",
    "quietAccumulationScore",
    "preBreakoutMomentumStage",
    "antiManipulationConfidenceScore",
    "signalPersistenceScore",
    "sniperState",
    "sniperQualified",
    "sniperScore",
    "confidenceAdjustedSniperScore",
    "sniperConfidence",
    "preConsensusGapScore",
    "sniperEvidenceConfidence",
    "sniperDataFreshness",
    "sniperSourceAgreement",
    "primarySniperOutcomeLabel",
    "pointInTimeStatus",
    "sniperBlockingReasons",
    "progressiveOpportunityScore",
    "marketOpportunityRank",
    "marketOpportunityRankLevel",
    "opportunityLane",
    "recommendedHorizon",
    "trustScore",
    "executionScore",
    "moneyRankScore",
    "moneyRank",
    "moneyRankEligible",
    "executableTradeSizeUsd",
    "opportunityRankingTier",
    "bestAvailableRank",
    "opportunityConfidence",
    "opportunityEvidenceCoverage",
    "opportunityWhyNowSignals",
    "missingEvidence",
    "opportunityHardBlockers",
    "emergingDiscoveryAIEligible",
    "opportunityScore",
    "marketAdjustedScore",
    "rawPipelineScore",
    "pipelineRank",
    "pipelinePercentile",
    "conviction",
    "allocationBucket",
    "watchlistPriority",
    "action",
    "xSocialScore",
    "externalSignalScore",
    "externalRiskScore",
    "aiAnalystScore",
    "aiDecision",
    "aiConfidence",
    "aiMemo",
    "proofScore",
    "proofStrength",
    "proofVerdict",
    "proofCarryingAlphaContractRank",
    "proofCarryingAlphaContractScore",
    "proofCarryingAlphaContractVerdict",
    "proofCarryingAlphaContractConfidence",
    "proofCarryingAlphaContractId",
    "proofCarryingAlphaContractLatestGrade",
    "proofCarryingAlphaContractCaveat",
    "alphaContractMustProve",
    "alphaContractInvalidationRules",
    "alphaKnowledgeGraphScore",
    "alphaKnowledgeGraphVerdict",
    "alphaKnowledgeGraphConfidence",
    "alphaKnowledgeGraphDominantRelation",
    "causalMarketTwinScore",
    "causalMarketTwinVerdict",
    "causalMarketTwinExpectedReturnPct",
    "causalMarketTwinUpsideProbability",
    "causalMarketTwinDownsideProbability",
    "causalMarketTwinPrimaryDriver",
    "autonomousCausalNetworkRank",
    "autonomousCausalNetworkScore",
    "autonomousCausalNetworkVerdict",
    "autonomousCausalProjectState",
    "autonomousCausalNetworkConfidence",
    "causalPatternSuccessRate",
    "causalPatternSampleSize",
    "causalEvidenceFragility",
    "causalEvidenceFragilityScore",
    "causalIndependentEvidenceFamilies",
    "causalNetworkNextConfirmation",
    "causalNetworkInvalidations",
    "alphaEvolutionGovernorRank",
    "alphaEvolutionGovernorScore",
    "alphaEvolutionGovernorVerdict",
    "alphaEvolutionGovernorAction",
    "alphaEvolutionGovernorReviewCadence",
    "alphaEvolutionGovernorBlockers",
    "alphaEvolutionGovernorMissingProof",
    "smallCapHunterSelected",
    "smallCapHunterSelectionRank",
    "smallCapHunterScore",
    "smallCapHunterVerdict",
    "smallCapMarketCap",
    "smallCapBand",
    "smallCapStructureScore",
    "smallCapUpsideScore",
    "smallCapExecutionScore",
    "smallCapRiskScore",
    "smallCapPurchaseRoute",
    "smallCapPurchaseRouteStatus",
    "smallCapPurchaseRouteScore",
    "smallCapDetectedRoutes",
    "smallCapPaperBudgetUsd",
    "smallCapLiquidityImpactPct",
    "smallCapWarnings",
    "executionTwinSelected",
    "executionTwinRank",
    "executionTwinScore",
    "executionTwinVerdict",
    "executionTwinConfidence",
    "executionTwinRoute",
    "executionTwinSlippagePct",
    "executionTwinSafetyBlockers",
    "organicIntegrityScore",
    "organicDemandScore",
    "economicSustainabilityScore",
    "organicDemandVerdict",
    "economicIntegrityRiskScore",
    "activityAuthenticityRiskScore",
    "supplyIntegrityRiskScore",
    "economicIntegrityScoreCap",
    "economicIntegrityScoreCapReasons",
    "organicDemandPromotionBlocked",
    "organicDemandManualReviewLabel",
    "economicIntegrityResearchTasks",
    "economicIntegrityPenalty",
    "hardExitLiquidityUsd",
    "organicActivityShare",
    "economicIntegrityBlockers",
    "institutionalDataProvenanceScore",
    "institutionalDataReadiness",
    "institutionalDataSourceCount",
    "institutionalDataSourceFamilyCount",
    "institutionalDataBlockers",
    "confidenceAdjustedRank",
    "confidenceAdjustedScore",
    "institutionalRankScore",
    "narrativeHeatScore",
    "narrativeHeatState",
    "projectChangeScore",
    "projectChangeState",
    "sourceReliabilityScore",
    "trapRiskScore",
    "trapRiskLevel",
    "aiEcosystemScore",
    "aiEcosystemVerdict",
    "aiEcosystemConfidence",
    "aiEcosystemCaveat",
    "strongBuyLifecycleStage",
    "bestTimeframe",
    "redTeamStatus",
    "redTeamScore",
    "aiDisagreementLevel",
    "aiDisagreementScore",
    "alphaLabScore",
    "alphaLabStatus",
    "alphaLabBestStrategy",
    "quantumBrainScore",
    "quantumDecisionState",
    "quantumBullProbability",
    "quantumBearProbability",
    "convictionEntropy",
    "worldModelScore",
    "marketRegimeGovernor",
    "marketScientistScore",
    "falsePositiveRisk",
    "humanPreferenceFit",
    "simulationPortfolioRank",
    "simulationBrainScore",
    "marketMemoryTwinScore",
    "simulationDecision",
    "simulationConfidence",
    "breakoutProbability30d",
    "expectedReturn30dPct",
    "expectedReturn90dPct",
    "bearCaseDrawdownPct",
    "falsePositiveSimilarity",
    "closestMarketAnalog",
    "engineTournamentConsensus",
    "adversarialSimulationStatus",
    "outcomeJudgeScore",
    "outcomeJudgeStatus",
    "outcomeJudgeVerdict",
    "outcomeRealityAdjustment",
    "outcomeAdjustedConfidence",
    "outcomePriceChangePct",
    "outcomeGrade",
    "liveCatalystRadarScore",
    "liveCatalystUrgency",
    "liveCatalystAction",
    "liveCatalystTopEvent",
    "dossierSwarmScore",
    "dossierSwarmDecision",
    "dossierSwarmConsensus",
    "dossierKeyBullCase",
    "dossierKeyBearCase",
    "dossierMustVerify",
    "whyThisMatters",
    "topEvidence",
    "topRisks",
    "dataConfidence",
    "dataConfidenceScore",
    "institutionalVNextScore",
    "institutionalConfidenceScore",
    "institutionalConfidenceLevel",
    "evidenceQualityScore",
    "smartMoneyConvictionScore",
    "liquidityMigrationScore",
    "vestingPressureScore",
    "tokenUnlockRiskScore",
    "monteCarloV2Score",
    "explainabilitySummary",
    "institutionalWatchScore",
    "learningEdgeScore",
    "outcomeLearningScore",
    "outcomeWinRate",
    "outcomeTrapRisk",
    "prePumpPatternScore",
    "prePumpPatternMatchPct",
    "trapPatternMatchPct",
    "prePumpPatternEdge",
    "prePumpPatternConfidence",
    "signalCombinationScore",
    "signalCombinationEdge",
    "calibrationScore",
    "calibrationAdjustment",
    "calibrationConfidence",
    "calibrationSupportSignals",
    "calibrationWarningSignals",
    "winningCombinations",
    "trapCombinations",
    "scoreTrend",
    "quantumOpportunityScore",
    "quantumFieldState",
    "quantumExpectedReturnPct",
    "quantumBestCaseReturnPct",
    "quantumWorstCaseReturnPct",
    "quantumPositiveProbability",
    "quantumCollapseProbability",
    "riskScore",
    "riskFlags",
    "alphaTags",
    "marketRegime",
    "confidence",
    "marketCap",
    "volume24h",
    "liquidity",
    "narrative",
    "tier",
  ];

  const rows = projects.map((p, index) => [
    index + 1,
    p.name,
    p.symbol,
    p.chain,
    p.finalSelectionState ?? "",
    p.finalSelectionQualified ? "yes" : "",
    p.finalIntegrityScore ?? "",
    p.finalIntegrityVerdict ?? "",
    Array.isArray(p.finalBlockingReasons) ? p.finalBlockingReasons.join("; ") : "",
    Array.isArray(p.finalWarningReasons) ? p.finalWarningReasons.join("; ") : "",
    p.finalIdentityState ?? "",
    p.permanentProjectKey ?? "",
    p.purchaseRouteConfirmed ? "yes" : "",
    p.executionRouteAvailable ? "yes" : "",
    p.liquidityVerified ? "yes" : "",
    p.preConsensusRank ?? "",
    p.preConsensusCandidateType ?? "",
    p.preConsensusTier ?? "",
    p.preConsensusOpportunityScore ?? "",
    p.regimeAdjustedOpportunityScore ?? "",
    p.informationAdvantageScore ?? "",
    p.estimatedConsensusStage ?? "",
    p.quietAccumulationDetected ? "yes" : "",
    p.quietAccumulationScore ?? "",
    p.preBreakoutMomentumStage ?? "",
    p.antiManipulationConfidenceScore ?? "",
    p.signalPersistenceScore ?? "",
    p.sniperState ?? "",
    p.sniperQualified ? "yes" : "",
    p.sniperScore ?? "",
    p.confidenceAdjustedSniperScore ?? "",
    p.sniperConfidence ?? "",
    p.preConsensusGapScore ?? "",
    p.sniperEvidenceConfidence ?? "",
    p.sniperDataFreshness ?? "",
    p.sniperSourceAgreement ?? "",
    p.primarySniperOutcomeLabel ?? "",
    p.pointInTimeStatus ?? "",
    Array.isArray(p.sniperBlockingReasons) ? p.sniperBlockingReasons.join("; ") : "",
    p.progressiveOpportunityScore ?? p.opportunityScoreV2 ?? "",
    p.marketOpportunityRank ?? p.marketOpportunityRankScore ?? "",
    p.marketOpportunityRankLevel ?? "",
    p.opportunityLane ?? "",
    p.recommendedHorizon ?? "",
    p.trustScore ?? p.progressiveTrustScore ?? "",
    p.executionScore ?? p.progressiveExecutionScore ?? "",
    p.moneyRankScore ?? "",
    p.moneyRank ?? "",
    p.moneyRankEligible ? "yes" : "",
    p.executableTradeSizeUsd ?? "",
    p.opportunityRankingTier ?? "",
    p.bestAvailableRank ?? "",
    p.opportunityConfidence ?? "",
    p.opportunityEvidenceCoverage ?? "",
    Array.isArray(p.opportunityWhyNowSignals)
      ? p.opportunityWhyNowSignals.map((signal) => `${signal.label || "signal"}:${signal.score ?? ""}`).join("; ")
      : "",
    Array.isArray(p.missingEvidence) ? p.missingEvidence.join("; ") : "",
    Array.isArray(p.opportunityHardBlockers) ? p.opportunityHardBlockers.join("; ") : "",
    p.emergingDiscoveryAIEligible ? "yes" : "",
    p.opportunityScore ?? p.score ?? 0,
    p.marketAdjustedScore ?? p.pipelineScore ?? 0,
    p.rawPipelineScore ?? "",
    p.pipelineRank ?? index + 1,
    p.pipelinePercentile ?? "",
    p.conviction ?? "",
    p.allocationBucket ?? "",
    p.watchlistPriority ?? "",
    p.executionPlan?.action ?? "",
    p.xSocialScore ?? "",
    p.externalSignalScore ?? "",
    p.externalRiskScore ?? "",
    p.aiAnalystScore ?? "",
    p.aiDecision ?? "",
    p.aiConfidence ?? "",
    p.aiThesis?.memo ?? "",
    p.proofScore ?? "",
    p.proofStrength ?? "",
    p.proofVerdict ?? "",
    p.proofCarryingAlphaContractRank ?? "",
    p.proofCarryingAlphaContractScore ?? "",
    p.proofCarryingAlphaContractVerdict ?? "",
    p.proofCarryingAlphaContract?.confidenceNow ?? "",
    p.proofCarryingAlphaContract?.contractId ?? "",
    p.proofCarryingAlphaContract?.latestGrade?.grade ?? "",
    p.proofCarryingAlphaContract?.fallbackCaveat ?? p.alphaContractReceipt?.caveat ?? "",
    Array.isArray(p.alphaContractReceipt?.mustProve)
      ? p.alphaContractReceipt.mustProve.join("; ")
      : "",
    Array.isArray(p.alphaContractReceipt?.invalidationRules)
      ? p.alphaContractReceipt.invalidationRules.join("; ")
      : "",
    p.alphaKnowledgeGraphScore ?? "",
    p.alphaKnowledgeGraphVerdict ?? "",
    p.alphaKnowledgeGraphConfidence ?? "",
    p.alphaKnowledgeGraph?.dominantRelation ?? "",
    p.causalMarketTwinScore ?? "",
    p.causalMarketTwinVerdict ?? "",
    p.causalMarketTwinExpectedReturnPct ?? "",
    p.causalMarketTwinUpsideProbability ?? "",
    p.causalMarketTwinDownsideProbability ?? "",
    p.causalMarketTwin?.primaryCausalDriver ?? "",
    p.autonomousCausalNetworkRank ?? "",
    p.autonomousCausalNetworkScore ?? "",
    p.autonomousCausalNetworkVerdict ?? "",
    p.autonomousCausalProjectState ?? "",
    p.autonomousCausalNetworkConfidence ?? "",
    p.causalPatternSuccessRate ?? "",
    p.causalPatternSampleSize ?? "",
    p.causalEvidenceFragility ?? "",
    p.causalEvidenceFragilityScore ?? "",
    Array.isArray(p.causalIndependentEvidenceFamilies)
      ? p.causalIndependentEvidenceFamilies.join("; ")
      : "",
    p.autonomousCausalAlphaNetwork?.hypothesis?.nextRequiredConfirmation ?? "",
    Array.isArray(p.autonomousCausalAlphaNetwork?.hypothesis?.invalidations)
      ? p.autonomousCausalAlphaNetwork.hypothesis.invalidations.join("; ")
      : "",
    p.alphaEvolutionGovernorRank ?? "",
    p.alphaEvolutionGovernorScore ?? "",
    p.alphaEvolutionGovernorVerdict ?? "",
    p.alphaEvolutionGovernor?.actionPlan?.primaryAction ?? "",
    p.alphaEvolutionGovernor?.actionPlan?.reviewCadence ?? "",
    Array.isArray(p.alphaEvolutionGovernor?.blockers)
      ? p.alphaEvolutionGovernor.blockers.join("; ")
      : "",
    Array.isArray(p.alphaEvolutionGovernor?.missingProof)
      ? p.alphaEvolutionGovernor.missingProof.join("; ")
      : "",
    p.smallCapHunterSelected ? "yes" : "",
    p.smallCapHunterSelectionRank ?? "",
    p.smallCapHunterScore ?? "",
    p.smallCapHunterVerdict ?? "",
    p.smallCapMarketCap ?? "",
    p.smallCapBand ?? "",
    p.smallCapStructureScore ?? "",
    p.smallCapUpsideScore ?? "",
    p.smallCapExecutionScore ?? "",
    p.smallCapRiskScore ?? "",
    p.smallCapHunter?.purchaseRoute?.preferredRoute ?? "",
    p.smallCapHunter?.purchaseRoute?.status ?? "",
    p.smallCapHunter?.purchaseRoute?.score ?? "",
    Array.isArray(p.smallCapHunter?.purchaseRoute?.routes)
      ? p.smallCapHunter.purchaseRoute.routes.map((route) => route.type).join("; ")
      : "",
    p.smallCapHunter?.paperPlan?.totalPaperBudgetUsd ?? "",
    p.smallCapHunter?.execution?.estimatedLiquidityImpactPct ?? "",
    Array.isArray(p.smallCapHunter?.warnings)
      ? p.smallCapHunter.warnings.join("; ")
      : "",
    p.proofOfAlphaExecutionTwinSelected ? "yes" : "",
    p.proofOfAlphaExecutionTwinRank ?? "",
    p.proofOfAlphaExecutionTwinScore ?? "",
    p.proofOfAlphaExecutionTwinVerdict ?? "",
    p.proofOfAlphaExecutionTwinConfidence ?? "",
    p.proofOfAlphaExecutionTwinRoute ?? "",
    p.proofOfAlphaExecutionTwinSlippagePct ?? "",
    Array.isArray(p.proofOfAlphaExecutionTwin?.safety?.blockers)
      ? p.proofOfAlphaExecutionTwin.safety.blockers.join("; ")
      : "",
    p.organicEconomicIntegrityScore ?? "",
    p.organicDemandScore ?? "",
    p.economicSustainabilityScore ?? "",
    p.organicDemandVerdict ?? "",
    p.economicIntegrityRiskScore ?? "",
    p.activityAuthenticityRiskScore ?? "",
    p.supplyIntegrityRiskScore ?? "",
    p.economicIntegrityScoreCap ?? "",
    Array.isArray(p.economicIntegrityScoreCapReasons)
      ? p.economicIntegrityScoreCapReasons.join("; ")
      : "",
    p.organicDemandPromotionBlocked ? "true" : "false",
    p.organicDemandManualReviewLabel ?? "",
    Array.isArray(p.economicIntegrityResearchTasks)
      ? p.economicIntegrityResearchTasks.map((task) => `${task.priority || "open"}:${task.title || task.id}`).join("; ")
      : "",
    p.economicIntegrityPenalty ?? "",
    p.hardExitLiquidityUsd ?? "",
    p.organicActivityShare ?? "",
    Array.isArray(p.economicIntegrityBlockers)
      ? p.economicIntegrityBlockers.join("; ")
      : "",
    p.institutionalDataProvenanceScore ?? p.institutionalDataProvenance?.score ?? "",
    p.institutionalDataReadiness ?? p.institutionalDataProvenance?.institutionalReadiness ?? "",
    p.institutionalDataSourceCount ?? p.institutionalDataProvenance?.sourceSummary?.sourceCount ?? "",
    p.institutionalDataSourceFamilyCount ?? p.institutionalDataProvenance?.sourceSummary?.sourceFamilyCount ?? "",
    Array.isArray(p.institutionalDataBlockers)
      ? p.institutionalDataBlockers.join("; ")
      : Array.isArray(p.institutionalDataProvenance?.blockers)
      ? p.institutionalDataProvenance.blockers.join("; ")
      : "",
    p.confidenceAdjustedRank ?? "",
    p.confidenceAdjustedScore ?? "",
    p.institutionalRankScore ?? "",
    p.narrativeHeatScore ?? "",
    p.narrativeHeatState ?? "",
    p.projectChangeScore ?? "",
    p.projectChangeState ?? "",
    p.sourceReliabilityScore ?? "",
    p.trapRiskScore ?? "",
    p.trapRiskLevel ?? "",
    p.aiEcosystemScore ?? "",
    p.aiEcosystemVerdict ?? "",
    p.aiEcosystemConfidence ?? "",
    p.aiEcosystemCaveat ?? "",
    p.strongBuyLifecycleStage ?? "",
    p.multiTimeframeIntelligence?.bestHorizon ?? "",
    p.redTeamReview?.status ?? "",
    p.redTeamReview?.score ?? "",
    p.aiDisagreement?.level ?? "",
    p.aiDisagreement?.score ?? "",
    p.alphaLabScore ?? "",
    p.alphaLabStatus ?? "",
    p.alphaLabBestStrategy?.name ?? "",
    p.quantumBrainScore ?? "",
    p.quantumDecisionState ?? "",
    p.quantumBullProbability ?? "",
    p.quantumBearProbability ?? "",
    p.convictionEntropy ?? "",
    p.worldModelScore ?? "",
    p.marketRegimeGovernor?.regime ?? "",
    p.marketScientistScore ?? "",
    p.falsePositiveAutopsy?.falsePositiveRisk ?? "",
    p.humanPreferenceFit?.score ?? "",
    p.simulationPortfolioRank ?? "",
    p.simulationBrainScore ?? "",
    p.marketMemoryTwinScore ?? "",
    p.simulationDecision ?? "",
    p.simulationConfidence ?? "",
    p.breakoutProbability30d ?? "",
    p.expectedReturn30dPct ?? "",
    p.expectedReturn90dPct ?? "",
    p.bearCaseDrawdownPct ?? "",
    p.falsePositiveSimilarity ?? "",
    p.closestMarketAnalogs?.[0]?.name ?? "",
    p.engineTournament?.consensus ?? "",
    p.adversarialSimulationReview?.status ?? "",
    p.outcomeJudgeScore ?? "",
    p.outcomeJudgeStatus ?? "",
    p.outcomeJudgeVerdict ?? "",
    p.outcomeRealityAdjustment ?? "",
    p.outcomeAdjustedConfidence ?? "",
    p.outcomeJudgement?.outcome?.priceChangePct ?? "",
    p.outcomeJudgement?.grade?.label ?? "",
    p.liveCatalystRadarScore ?? "",
    p.liveCatalystUrgency ?? "",
    p.liveCatalystAction ?? "",
    p.liveCatalystEvents?.[0]?.type ?? "",
    p.dossierSwarmScore ?? "",
    p.dossierSwarmDecision ?? "",
    p.dossierSwarmConsensus ?? "",
    p.projectDossierSwarm?.keyBullCase ?? "",
    p.projectDossierSwarm?.keyBearCase ?? "",
    Array.isArray(p.projectDossierSwarm?.mustVerify)
      ? p.projectDossierSwarm.mustVerify.join("; ")
      : "",
    p.whyThisMatters ?? "",
    Array.isArray(p.topEvidence)
      ? p.topEvidence.map((item) => item.text || item.label || item.summary).filter(Boolean).join("; ")
      : "",
    Array.isArray(p.topRisks)
      ? p.topRisks.map((item) => item.text || item.label || item.summary).filter(Boolean).join("; ")
      : "",
    p.dataConfidence ?? "",
    p.dataConfidenceScore ?? "",
    p.institutionalVNextScore ?? "",
    p.institutionalConfidenceScore ?? "",
    p.institutionalConfidenceLevel ?? "",
    p.evidenceQualityScore ?? "",
    p.smartMoneyConvictionScore ?? "",
    p.liquidityMigrationScore ?? "",
    p.vestingPressureScore ?? "",
    p.tokenUnlockRiskScore ?? "",
    p.monteCarloV2Score ?? "",
    p.explainabilitySummary ?? "",
    p.institutionalWatchScore ?? "",
    p.learningEdgeScore ?? "",
    p.outcomeLearningScore ?? "",
    p.outcomeLearning?.estimatedWinRate ?? p.outcomeWinRate ?? "",
    p.outcomeTrapRisk ?? "",
    p.prePumpPatternScore ?? "",
    p.prePumpPatternMatchPct ?? "",
    p.trapPatternMatchPct ?? "",
    p.prePumpPatternEdge ?? "",
    p.prePumpPatternConfidence ?? "",
    p.signalCombinationScore ?? "",
    p.signalCombinationEdge ?? "",
    p.calibrationScore ?? "",
    p.calibrationAdjustment ?? "",
    p.calibrationConfidence ?? "",
    Array.isArray(p.calibrationSignals)
      ? p.calibrationSignals.map((signal) => signal.label).join("; ")
      : "",
    Array.isArray(p.calibrationRiskSignals)
      ? p.calibrationRiskSignals.map((signal) => signal.label).join("; ")
      : "",
    Array.isArray(p.winningSignalCombinations)
      ? p.winningSignalCombinations.map((combo) => combo.name).join("; ")
      : "",
    Array.isArray(p.trapSignalCombinations)
      ? p.trapSignalCombinations.map((combo) => combo.name).join("; ")
      : "",
    p.projectWatchChange?.scoreTrend ?? p.institutionalLearning?.scoreTrend ?? "",
    p.quantumOpportunityScore ?? "",
    p.quantumFieldState ?? "",
    p.quantumOutcomeField?.expectedReturnPct ?? "",
    p.quantumOutcomeField?.bestCaseReturnPct ?? "",
    p.quantumOutcomeField?.worstCaseReturnPct ?? "",
    p.quantumOutcomeField?.positiveProbability ?? "",
    p.quantumOutcomeField?.collapseProbability ?? "",
    p.riskScore ?? 0,
    Array.isArray(p.riskFlags) ? p.riskFlags.join("; ") : "",
    Array.isArray(p.alphaTags) ? p.alphaTags.join("; ") : "",
    p.marketRegime ?? "",
    p.confidence ?? "",
    p.marketCap ?? "",
    p.volume24h ?? p.volume ?? "",
    p.liquidity ?? "",
    p.narrative ?? "",
    p.tier ?? "",
  ]);

  const csv = [
    headers.join(","),
    ...rows.map((row) => row.map((v) => `"${clean(v)}"`).join(",")),
  ].join("\n");

  const filePath = path.join(reportsDir, "opportunities.csv");
  fs.writeFileSync(filePath, csv);

  return filePath;
}
