import fs from "fs";
import path from "path";

function clean(value = "") {
  return String(value ?? "")
    .replace(/"/g, '""')
    .replace(/\n/g, " ")
    .trim();
}

export function writeCsvReport(projects = []) {
  const reportsDir = path.resolve("reports");
  fs.mkdirSync(reportsDir, { recursive: true });

  const headers = [
    "rank",
    "name",
    "symbol",
    "chain",
    "opportunityScore",
    "marketAdjustedScore",
    "rawPipelineScore",
    "pipelineRank",
    "pipelinePercentile",
    "conviction",
    "allocationBucket",
    "watchlistPriority",
    "action",
    "xSocialScore",
    "externalSignalScore",
    "externalRiskScore",
    "aiAnalystScore",
    "aiDecision",
    "aiConfidence",
    "aiMemo",
    "proofScore",
    "proofStrength",
    "proofVerdict",
    "confidenceAdjustedRank",
    "confidenceAdjustedScore",
    "institutionalRankScore",
    "narrativeHeatScore",
    "narrativeHeatState",
    "projectChangeScore",
    "projectChangeState",
    "sourceReliabilityScore",
    "trapRiskScore",
    "trapRiskLevel",
    "aiEcosystemScore",
    "aiEcosystemVerdict",
    "aiEcosystemConfidence",
    "aiEcosystemCaveat",
    "strongBuyLifecycleStage",
    "bestTimeframe",
    "redTeamStatus",
    "redTeamScore",
    "aiDisagreementLevel",
    "aiDisagreementScore",
    "alphaLabScore",
    "alphaLabStatus",
    "alphaLabBestStrategy",
    "quantumBrainScore",
    "quantumDecisionState",
    "quantumBullProbability",
    "quantumBearProbability",
    "convictionEntropy",
    "worldModelScore",
    "marketRegimeGovernor",
    "marketScientistScore",
    "falsePositiveRisk",
    "humanPreferenceFit",
    "simulationPortfolioRank",
    "simulationBrainScore",
    "marketMemoryTwinScore",
    "simulationDecision",
    "simulationConfidence",
    "breakoutProbability30d",
    "expectedReturn30dPct",
    "expectedReturn90dPct",
    "bearCaseDrawdownPct",
    "falsePositiveSimilarity",
    "closestMarketAnalog",
    "engineTournamentConsensus",
    "adversarialSimulationStatus",
    "outcomeJudgeScore",
    "outcomeJudgeStatus",
    "outcomeJudgeVerdict",
    "outcomeRealityAdjustment",
    "outcomeAdjustedConfidence",
    "outcomePriceChangePct",
    "outcomeGrade",
    "dossierSwarmScore",
    "dossierSwarmDecision",
    "dossierSwarmConsensus",
    "dossierKeyBullCase",
    "dossierKeyBearCase",
    "dossierMustVerify",
    "whyThisMatters",
    "topEvidence",
    "topRisks",
    "dataConfidence",
    "dataConfidenceScore",
    "institutionalVNextScore",
    "institutionalConfidenceScore",
    "institutionalConfidenceLevel",
    "evidenceQualityScore",
    "smartMoneyConvictionScore",
    "liquidityMigrationScore",
    "vestingPressureScore",
    "tokenUnlockRiskScore",
    "monteCarloV2Score",
    "explainabilitySummary",
    "institutionalWatchScore",
    "learningEdgeScore",
    "outcomeLearningScore",
    "outcomeWinRate",
    "outcomeTrapRisk",
    "prePumpPatternScore",
    "prePumpPatternMatchPct",
    "trapPatternMatchPct",
    "prePumpPatternEdge",
    "prePumpPatternConfidence",
    "signalCombinationScore",
    "signalCombinationEdge",
    "calibrationScore",
    "calibrationAdjustment",
    "calibrationConfidence",
    "calibrationSupportSignals",
    "calibrationWarningSignals",
    "winningCombinations",
    "trapCombinations",
    "scoreTrend",
    "quantumOpportunityScore",
    "quantumFieldState",
    "quantumExpectedReturnPct",
    "quantumBestCaseReturnPct",
    "quantumWorstCaseReturnPct",
    "quantumPositiveProbability",
    "quantumCollapseProbability",
    "riskScore",
    "riskFlags",
    "alphaTags",
    "marketRegime",
    "confidence",
    "marketCap",
    "volume24h",
    "liquidity",
    "narrative",
    "tier",
  ];

  const rows = projects.map((p, index) => [
    index + 1,
    p.name,
    p.symbol,
    p.chain,
    p.opportunityScore ?? p.score ?? 0,
    p.marketAdjustedScore ?? p.pipelineScore ?? 0,
    p.rawPipelineScore ?? "",
    p.pipelineRank ?? index + 1,
    p.pipelinePercentile ?? "",
    p.conviction ?? "",
    p.allocationBucket ?? "",
    p.watchlistPriority ?? "",
    p.executionPlan?.action ?? "",
    p.xSocialScore ?? "",
    p.externalSignalScore ?? "",
    p.externalRiskScore ?? "",
    p.aiAnalystScore ?? "",
    p.aiDecision ?? "",
    p.aiConfidence ?? "",
    p.aiThesis?.memo ?? "",
    p.proofScore ?? "",
    p.proofStrength ?? "",
    p.proofVerdict ?? "",
    p.confidenceAdjustedRank ?? "",
    p.confidenceAdjustedScore ?? "",
    p.institutionalRankScore ?? "",
    p.narrativeHeatScore ?? "",
    p.narrativeHeatState ?? "",
    p.projectChangeScore ?? "",
    p.projectChangeState ?? "",
    p.sourceReliabilityScore ?? "",
    p.trapRiskScore ?? "",
    p.trapRiskLevel ?? "",
    p.aiEcosystemScore ?? "",
    p.aiEcosystemVerdict ?? "",
    p.aiEcosystemConfidence ?? "",
    p.aiEcosystemCaveat ?? "",
    p.strongBuyLifecycleStage ?? "",
    p.multiTimeframeIntelligence?.bestHorizon ?? "",
    p.redTeamReview?.status ?? "",
    p.redTeamReview?.score ?? "",
    p.aiDisagreement?.level ?? "",
    p.aiDisagreement?.score ?? "",
    p.alphaLabScore ?? "",
    p.alphaLabStatus ?? "",
    p.alphaLabBestStrategy?.name ?? "",
    p.quantumBrainScore ?? "",
    p.quantumDecisionState ?? "",
    p.quantumBullProbability ?? "",
    p.quantumBearProbability ?? "",
    p.convictionEntropy ?? "",
    p.worldModelScore ?? "",
    p.marketRegimeGovernor?.regime ?? "",
    p.marketScientistScore ?? "",
    p.falsePositiveAutopsy?.falsePositiveRisk ?? "",
    p.humanPreferenceFit?.score ?? "",
    p.simulationPortfolioRank ?? "",
    p.simulationBrainScore ?? "",
    p.marketMemoryTwinScore ?? "",
    p.simulationDecision ?? "",
    p.simulationConfidence ?? "",
    p.breakoutProbability30d ?? "",
    p.expectedReturn30dPct ?? "",
    p.expectedReturn90dPct ?? "",
    p.bearCaseDrawdownPct ?? "",
    p.falsePositiveSimilarity ?? "",
    p.closestMarketAnalogs?.[0]?.name ?? "",
    p.engineTournament?.consensus ?? "",
    p.adversarialSimulationReview?.status ?? "",
    p.outcomeJudgeScore ?? "",
    p.outcomeJudgeStatus ?? "",
    p.outcomeJudgeVerdict ?? "",
    p.outcomeRealityAdjustment ?? "",
    p.outcomeAdjustedConfidence ?? "",
    p.outcomeJudgement?.outcome?.priceChangePct ?? "",
    p.outcomeJudgement?.grade?.label ?? "",
    p.dossierSwarmScore ?? "",
    p.dossierSwarmDecision ?? "",
    p.dossierSwarmConsensus ?? "",
    p.projectDossierSwarm?.keyBullCase ?? "",
    p.projectDossierSwarm?.keyBearCase ?? "",
    Array.isArray(p.projectDossierSwarm?.mustVerify)
      ? p.projectDossierSwarm.mustVerify.join("; ")
      : "",
    p.whyThisMatters ?? "",
    Array.isArray(p.topEvidence)
      ? p.topEvidence.map((item) => item.text || item.label || item.summary).filter(Boolean).join("; ")
      : "",
    Array.isArray(p.topRisks)
      ? p.topRisks.map((item) => item.text || item.label || item.summary).filter(Boolean).join("; ")
      : "",
    p.dataConfidence ?? "",
    p.dataConfidenceScore ?? "",
    p.institutionalVNextScore ?? "",
    p.institutionalConfidenceScore ?? "",
    p.institutionalConfidenceLevel ?? "",
    p.evidenceQualityScore ?? "",
    p.smartMoneyConvictionScore ?? "",
    p.liquidityMigrationScore ?? "",
    p.vestingPressureScore ?? "",
    p.tokenUnlockRiskScore ?? "",
    p.monteCarloV2Score ?? "",
    p.explainabilitySummary ?? "",
    p.institutionalWatchScore ?? "",
    p.learningEdgeScore ?? "",
    p.outcomeLearningScore ?? "",
    p.outcomeLearning?.estimatedWinRate ?? p.outcomeWinRate ?? "",
    p.outcomeTrapRisk ?? "",
    p.prePumpPatternScore ?? "",
    p.prePumpPatternMatchPct ?? "",
    p.trapPatternMatchPct ?? "",
    p.prePumpPatternEdge ?? "",
    p.prePumpPatternConfidence ?? "",
    p.signalCombinationScore ?? "",
    p.signalCombinationEdge ?? "",
    p.calibrationScore ?? "",
    p.calibrationAdjustment ?? "",
    p.calibrationConfidence ?? "",
    Array.isArray(p.calibrationSignals)
      ? p.calibrationSignals.map((signal) => signal.label).join("; ")
      : "",
    Array.isArray(p.calibrationRiskSignals)
      ? p.calibrationRiskSignals.map((signal) => signal.label).join("; ")
      : "",
    Array.isArray(p.winningSignalCombinations)
      ? p.winningSignalCombinations.map((combo) => combo.name).join("; ")
      : "",
    Array.isArray(p.trapSignalCombinations)
      ? p.trapSignalCombinations.map((combo) => combo.name).join("; ")
      : "",
    p.projectWatchChange?.scoreTrend ?? p.institutionalLearning?.scoreTrend ?? "",
    p.quantumOpportunityScore ?? "",
    p.quantumFieldState ?? "",
    p.quantumOutcomeField?.expectedReturnPct ?? "",
    p.quantumOutcomeField?.bestCaseReturnPct ?? "",
    p.quantumOutcomeField?.worstCaseReturnPct ?? "",
    p.quantumOutcomeField?.positiveProbability ?? "",
    p.quantumOutcomeField?.collapseProbability ?? "",
    p.riskScore ?? 0,
    Array.isArray(p.riskFlags) ? p.riskFlags.join("; ") : "",
    Array.isArray(p.alphaTags) ? p.alphaTags.join("; ") : "",
    p.marketRegime ?? "",
    p.confidence ?? "",
    p.marketCap ?? "",
    p.volume24h ?? p.volume ?? "",
    p.liquidity ?? "",
    p.narrative ?? "",
    p.tier ?? "",
  ]);

  const csv = [
    headers.join(","),
    ...rows.map((row) => row.map((v) => `"${clean(v)}"`).join(",")),
  ].join("\n");

  const filePath = path.join(reportsDir, "opportunities.csv");
  fs.writeFileSync(filePath, csv);

  return filePath;
}
