import fs from "fs";
import path from "path";

const REPORTS_DIR = path.resolve("reports");
const DOCS_DIR = path.resolve("docs");

const PUBLIC_REPORTS = [
  "report.html",
  "report.json",
  "opportunities.csv",
  "alerts.json",
  "daily-brief.json",
  "watchtower-performance.json",
  "watchlist.json",
  "summary.txt",
  "quantum-field.json",
  "outcome-calibration.json",
  "pre-pump-patterns.json",
  "institutional-vnext.json",
  "state-of-art-signals.json",
  "ai-council.json",
  "agent-performance.json",
  "research-os.json",
  "alpha-lab.json",
];

function copyIfExists(fileName = "") {
  const source = path.join(REPORTS_DIR, fileName);
  const target = path.join(DOCS_DIR, fileName);

  if (!fs.existsSync(source)) return false;

  fs.copyFileSync(source, target);
  return true;
}

function writeLandingPage(copiedFiles = []) {
  const generatedAt = new Date().toISOString();
  const links = copiedFiles
    .filter((fileName) => fileName !== "report.html")
    .map((fileName) => `<a href="./${fileName}">${fileName}</a>`)
    .join("");

  const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Crypto Launch Intelligence Live Dashboard</title>
  <style>
    :root {
      color-scheme: dark;
      --bg: #071015;
      --panel: #101b23;
      --panel-2: #142532;
      --text: #edf7f2;
      --muted: #94a8b0;
      --line: #24404f;
      --green: #45e08f;
      --blue: #5fb7ff;
      --amber: #f2bd55;
    }

    * {
      box-sizing: border-box;
    }

    body {
      margin: 0;
      min-height: 100vh;
      background: var(--bg);
      color: var(--text);
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }

    header {
      border-bottom: 1px solid var(--line);
      padding: 24px clamp(18px, 4vw, 42px);
    }

    h1 {
      margin: 0;
      font-size: clamp(26px, 4vw, 46px);
      letter-spacing: 0;
    }

    .subtitle {
      color: var(--muted);
      margin-top: 8px;
      max-width: 820px;
      line-height: 1.5;
    }

    main {
      padding: 22px clamp(18px, 4vw, 42px) 42px;
    }

    .toolbar {
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 12px;
      flex-wrap: wrap;
      margin-bottom: 18px;
    }

    .status {
      color: var(--muted);
      font-size: 14px;
    }

    .actions {
      display: flex;
      gap: 10px;
      flex-wrap: wrap;
    }

    a {
      color: var(--text);
    }

    .button,
    .links a {
      display: inline-flex;
      align-items: center;
      min-height: 38px;
      border: 1px solid var(--line);
      border-radius: 8px;
      background: var(--panel);
      padding: 8px 12px;
      text-decoration: none;
      font-size: 14px;
    }

    .button.primary {
      border-color: rgba(69, 224, 143, 0.55);
      background: #12301f;
    }

    iframe {
      width: 100%;
      height: min(76vh, 920px);
      border: 1px solid var(--line);
      border-radius: 8px;
      background: var(--panel);
    }

    .links {
      display: flex;
      gap: 10px;
      flex-wrap: wrap;
      margin-top: 18px;
    }

    .empty {
      border: 1px solid var(--line);
      border-radius: 8px;
      background: var(--panel);
      padding: 18px;
      color: var(--muted);
      line-height: 1.5;
    }

    @media (max-width: 720px) {
      iframe {
        height: 72vh;
      }
    }
  </style>
</head>
<body>
  <header>
    <h1>Crypto Launch Intelligence</h1>
    <div class="subtitle">Live public dashboard generated by the scanner. It refreshes whenever the GitHub Pages workflow runs.</div>
  </header>
  <main>
    <div class="toolbar">
      <div class="status">Last published: ${generatedAt}</div>
      <div class="actions">
        <a class="button primary" href="./report.html">Open Full Dashboard</a>
        <a class="button" href="./report.json">JSON</a>
        <a class="button" href="./alerts.json">Alerts</a>
      </div>
    </div>
    ${
      copiedFiles.includes("report.html")
        ? '<iframe title="Crypto Launch Intelligence Report" src="./report.html"></iframe>'
        : '<div class="empty">No report has been generated yet. Run the scanner first, then publish the dashboard.</div>'
    }
    <div class="links">${links}</div>
  </main>
</body>
</html>
`.trim();

  fs.writeFileSync(path.join(DOCS_DIR, "index.html"), html);
}

export function publishGithubPagesDashboard() {
  fs.mkdirSync(DOCS_DIR, { recursive: true });

  const copiedFiles = PUBLIC_REPORTS.filter(copyIfExists);
  writeLandingPage(copiedFiles);

  return {
    outputDir: DOCS_DIR,
    copiedFiles,
    urlPath: "docs/index.html",
  };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const result = publishGithubPagesDashboard();
  console.log(JSON.stringify(result, null, 2));
}
