export const ENGINE_DEPENDENCY_MANIFEST = [
  {
    name: "Project Identity Graph",
    requiredInputs: ["name or symbol", "chain or source identity"],
    optionalInputs: ["tokenAddress", "poolAddress", "officialDomain"],
    producedFields: ["projectIdentity", "identityResolutionScore"],
    requiredUpstreamStages: [],
    timeout: 7000,
    failurePolicy: "fail-closed",
    mandatory: true,
    checkpointGroup: "identity",
  },
  {
    name: "Canonical Execution Route",
    requiredInputs: ["chain", "tokenAddress or exchange market", "poolAddress or venue"],
    optionalInputs: ["routeUrl", "quoteAsset"],
    producedFields: ["canonicalExecutionRoute", "canonicalExecutionRouteStatus"],
    requiredUpstreamStages: ["Project Identity Graph"],
    timeout: 7000,
    failurePolicy: "degrade",
    mandatory: true,
    checkpointGroup: "execution",
  },
  {
    name: "Execution Proof",
    requiredInputs: ["canonicalExecutionRoute", "priceUsd", "liquidityUsd"],
    optionalInputs: ["quoteTimestamp", "slippage", "sellSimulation"],
    producedFields: ["executionProof", "executionStatus", "moneyEvidence"],
    requiredUpstreamStages: ["Canonical Execution Route"],
    timeout: 7000,
    failurePolicy: "fail-closed",
    mandatory: true,
    checkpointGroup: "execution",
  },
  {
    name: "Capital Flow Baseline",
    requiredInputs: ["capitalFlowObservation", "historical observations"],
    optionalInputs: ["buyVolumeUsd", "sellVolumeUsd", "uniqueBuyers"],
    producedFields: ["capitalFlowBaseline", "capitalFlowBaselineStatus"],
    requiredUpstreamStages: ["Execution Proof"],
    timeout: 7000,
    failurePolicy: "degrade",
    mandatory: true,
    checkpointGroup: "capital-flow",
  },
  {
    name: "Capital Migration Core",
    requiredInputs: ["capitalFlowBaseline", "canonical identity", "execution proof"],
    optionalInputs: ["wallet concentration", "buyer breadth"],
    producedFields: ["capitalMigrationScore", "capitalMigrationLane"],
    requiredUpstreamStages: ["Capital Flow Baseline"],
    timeout: 7000,
    failurePolicy: "degrade",
    mandatory: true,
    checkpointGroup: "capital-flow",
  },
  {
    name: "Instant Safety Gate",
    requiredInputs: ["address or contract evidence", "risk evidence"],
    optionalInputs: ["securityEvidence", "honeypotEvidence"],
    producedFields: ["instantSafetyStatus", "instantSafetyScore"],
    requiredUpstreamStages: ["Project Identity Graph"],
    timeout: 7000,
    failurePolicy: "fail-closed",
    mandatory: true,
    checkpointGroup: "safety",
  },
  {
    name: "Small Cap Hunter",
    requiredInputs: ["capitalMigrationScore", "executionProof", "marketCap"],
    optionalInputs: ["catalysts", "safety", "liquidity"],
    producedFields: ["smallCapHunter", "smallCapHunterVerdict"],
    requiredUpstreamStages: ["Capital Migration Core", "Execution Proof"],
    timeout: 7000,
    failurePolicy: "degrade",
    mandatory: false,
    checkpointGroup: "ranking",
  },
  {
    name: "Proof of Alpha Execution Twin",
    requiredInputs: ["executionProof", "smallCapHunter"],
    optionalInputs: ["quote", "route"],
    producedFields: ["proofOfAlphaExecutionTwin", "proofOfAlphaExecutionTwinVerdict"],
    requiredUpstreamStages: ["Execution Proof", "Small Cap Hunter"],
    timeout: 7000,
    failurePolicy: "degrade",
    mandatory: false,
    checkpointGroup: "ranking",
  },
  {
    name: "Final Selection Integrity",
    requiredInputs: ["identity", "execution proof", "safety", "evidence"],
    optionalInputs: ["capitalMigrationScore", "vNextScore"],
    producedFields: ["finalSelectionState", "finalSelectionQualified"],
    requiredUpstreamStages: ["Execution Proof", "Capital Migration Core"],
    timeout: 7000,
    failurePolicy: "fail-closed",
    mandatory: true,
    checkpointGroup: "final",
  },
];

export function engineDependencyByName() {
  return new Map(ENGINE_DEPENDENCY_MANIFEST.map((engine) => [engine.name, engine]));
}
