export const ENGINE_DEPENDENCY_MANIFEST = [
  {
    name: "Project Identity Graph",
    requiredInputs: ["name or symbol", "chain or source identity"],
    optionalInputs: ["tokenAddress", "poolAddress", "officialDomain"],
    producedFields: ["projectIdentity", "identityResolutionScore"],
    requiredUpstreamStages: [],
    timeout: 7000,
    failurePolicy: "fail-closed",
    mandatory: true,
    checkpointGroup: "identity",
  },
  {
    name: "Canonical Execution Route",
    requiredInputs: ["chain", "tokenAddress or exchange market", "poolAddress or venue"],
    optionalInputs: ["routeUrl", "quoteAsset"],
    producedFields: ["canonicalExecutionRoute", "canonicalExecutionRouteStatus"],
    requiredUpstreamStages: ["Project Identity Graph"],
    timeout: 7000,
    failurePolicy: "degrade",
    mandatory: true,
    checkpointGroup: "execution",
  },
  {
    name: "Execution Proof Recovery",
    requiredInputs: ["canonicalExecutionRoute", "research priority or opportunity score"],
    optionalInputs: ["JUPITER_API_KEY", "ZEROX_API_KEY", "marketPair", "tokenAddress", "poolAddress"],
    producedFields: ["executionProofRecovery", "executionProofRecoveryRoute", "executionProofRecoveryStage"],
    requiredUpstreamStages: ["Canonical Execution Route"],
    timeout: 300000,
    failurePolicy: "degrade",
    mandatory: true,
    checkpointGroup: "execution",
  },
  {
    name: "Execution Proof",
    requiredInputs: ["canonicalExecutionRoute", "priceUsd", "liquidityUsd"],
    optionalInputs: ["executionProofRecovery", "quoteTimestamp", "slippage", "sellSimulation"],
    producedFields: ["executionProof", "executionStatus", "moneyEvidence"],
    requiredUpstreamStages: ["Canonical Execution Route", "Execution Proof Recovery"],
    timeout: 7000,
    failurePolicy: "fail-closed",
    mandatory: true,
    checkpointGroup: "execution",
  },
  {
    name: "Route Accessibility",
    requiredInputs: ["executionProof", "canonicalExecutionRoute", "chain or venue"],
    optionalInputs: ["preferred wallets", "preferred exchanges", "region", "bridge data"],
    producedFields: [
      "researchEligible",
      "qualityQualified",
      "executionReady",
      "userAccessible",
      "canonicalRoutes",
      "accessibilityLane",
      "opportunityRank",
      "accessibilityRank",
    ],
    requiredUpstreamStages: ["Execution Proof"],
    timeout: 7000,
    failurePolicy: "fail-closed",
    mandatory: true,
    checkpointGroup: "execution",
  },
  {
    name: "Candidate Truth Reconciliation",
    requiredInputs: ["canonical identity", "executionProof", "canonicalExecutionRoute"],
    optionalInputs: ["safetyProofStatus", "regionStatus", "executionProofRecoveryRoute"],
    producedFields: [
      "candidateProofState",
      "projectLifecycleState",
      "researchEligibilityState",
      "tradabilityState",
      "executionReadinessState",
    ],
    requiredUpstreamStages: ["Execution Proof", "Route Accessibility"],
    timeout: 7000,
    failurePolicy: "fail-closed",
    mandatory: true,
    checkpointGroup: "execution",
  },
  {
    name: "Candidate Decision Scoring",
    requiredInputs: ["candidateProofState", "highUpsideScalp classification", "research evidence"],
    optionalInputs: ["utility", "capital flow", "buyer breadth", "developer", "catalyst", "attention gap"],
    producedFields: [
      "researchOpportunityScore",
      "executionReadinessScore",
      "finalDecisionScore",
      "researchOpportunityCoverage",
      "executionReadinessCoverage",
    ],
    requiredUpstreamStages: ["Candidate Truth Reconciliation", "High-Upside Scalp Classification"],
    timeout: 7000,
    failurePolicy: "fail-closed",
    mandatory: true,
    checkpointGroup: "decision",
  },
  {
    name: "Capital Flow Baseline",
    requiredInputs: ["capitalFlowObservation", "historical observations"],
    optionalInputs: ["buyVolumeUsd", "sellVolumeUsd", "uniqueBuyers"],
    producedFields: ["capitalFlowBaseline", "capitalFlowBaselineStatus"],
    requiredUpstreamStages: ["Route Accessibility"],
    timeout: 7000,
    failurePolicy: "degrade",
    mandatory: true,
    checkpointGroup: "capital-flow",
  },
  {
    name: "Capital Migration Core",
    requiredInputs: ["capitalFlowBaseline", "canonical identity", "execution proof"],
    optionalInputs: ["wallet concentration", "buyer breadth"],
    producedFields: ["capitalMigrationScore", "capitalMigrationLane"],
    requiredUpstreamStages: ["Capital Flow Baseline"],
    timeout: 7000,
    failurePolicy: "degrade",
    mandatory: true,
    checkpointGroup: "capital-flow",
  },
  {
    name: "Instant Safety Gate",
    requiredInputs: ["address or contract evidence", "risk evidence"],
    optionalInputs: ["securityEvidence", "honeypotEvidence"],
    producedFields: ["instantSafetyStatus", "instantSafetyScore"],
    requiredUpstreamStages: ["Project Identity Graph"],
    timeout: 7000,
    failurePolicy: "fail-closed",
    mandatory: true,
    checkpointGroup: "safety",
  },
  {
    name: "Small Cap Hunter",
    requiredInputs: ["capitalMigrationScore", "executionProof", "marketCap"],
    optionalInputs: ["catalysts", "safety", "liquidity"],
    producedFields: ["smallCapHunter", "smallCapHunterVerdict"],
    requiredUpstreamStages: ["Capital Migration Core", "Execution Proof"],
    timeout: 7000,
    failurePolicy: "degrade",
    mandatory: false,
    checkpointGroup: "ranking",
  },
  {
    name: "Proof of Alpha Execution Twin",
    requiredInputs: ["executionProof", "smallCapHunter"],
    optionalInputs: ["quote", "route"],
    producedFields: ["proofOfAlphaExecutionTwin", "proofOfAlphaExecutionTwinVerdict"],
    requiredUpstreamStages: ["Execution Proof", "Small Cap Hunter"],
    timeout: 7000,
    failurePolicy: "degrade",
    mandatory: false,
    checkpointGroup: "ranking",
  },
  {
    name: "Final Selection Integrity",
    requiredInputs: ["identity", "execution proof", "safety", "evidence"],
    optionalInputs: ["capitalMigrationScore", "vNextScore"],
    producedFields: ["finalSelectionState", "finalSelectionQualified"],
    requiredUpstreamStages: ["Execution Proof", "Capital Migration Core"],
    timeout: 7000,
    failurePolicy: "fail-closed",
    mandatory: true,
    checkpointGroup: "final",
  },
];

export function engineDependencyByName() {
  return new Map(ENGINE_DEPENDENCY_MANIFEST.map((engine) => [engine.name, engine]));
}
