import fs from "node:fs";
import { loadOutcomeSnapshots } from "../learning/outcomeSnapshotStore.js";
import { loadExactMarketObservations } from "../production/exactMarketObservationLedger.js";
import { linkShadowPredictionsToOutcomes } from "../production/shadowOutcomeLinker.js";
import { evaluateLeadTimeModel } from "../production/leadTimeOptimization.js";
import { detectEarliestSeparatingCause } from "../production/earliestCauseDetector.js";
import { accountEvidenceValue } from "../production/evidenceValueAccounting.js";
import { writeAtomicJson } from "../production/atomicArtifactStore.js";
import { strictIdentityKey, timestamp, finite } from "../production/productionMath.js";

function readJson(file,fallback=null){try{return JSON.parse(fs.readFileSync(file,"utf8"))}catch{return fallback}}
function readJsonl(file){if(!fs.existsSync(file))return[];return fs.readFileSync(file,"utf8").split("\n").filter(Boolean).flatMap(line=>{try{return[JSON.parse(line)]}catch{return[]}})}
function buildLeadTimes(predictions,snapshots,targetPct=25,options={}){const asOfMs=timestamp(options.asOf||options.now||new Date().toISOString());const grouped=new Map();for(const s of snapshots){const k=strictIdentityKey(s),at=timestamp(s.timestamp||s.observedAt);if(!k||at===null||asOfMs===null||at>asOfMs)continue;if(!grouped.has(k))grouped.set(k,[]);grouped.get(k).push(s);}for(const v of grouped.values())v.sort((a,b)=>(timestamp(a.timestamp||a.observedAt)||0)-(timestamp(b.timestamp||b.observedAt)||0));const rows=[];for(const p of predictions){const predictionKey=strictIdentityKey(p);if(!predictionKey)continue;const start=finite(p.priceUsd),startAt=timestamp(p.decisionAt||p.generatedAt);if(start===null||start<=0||startAt===null||asOfMs===null||startAt>asOfMs)continue;const target=start*(1+targetPct/100);const hit=(grouped.get(predictionKey)||[]).find(s=>{const t=timestamp(s.timestamp||s.observedAt),px=finite(s.priceUsd);return t!==null&&t>startAt&&t<=asOfMs&&px!==null&&px>=target;});const final=(grouped.get(predictionKey)||[]).filter(s=>{const t=timestamp(s.timestamp||s.observedAt);return t!==null&&t>startAt&&t<=asOfMs;}).at(-1);const realized=final&&finite(final.priceUsd)!==null?((finite(final.priceUsd)/start)-1)*100:null;rows.push({...p,hit:Boolean(hit),leadTimeHours:hit?((timestamp(hit.timestamp||hit.observedAt)-startAt)/3600000):null,realizedReturnPct:realized});}return rows;}
export function runMarketDiscoveryLearningCycle(options={}){const now=options.now||new Date().toISOString();const predictions=options.predictions||readJsonl("data/market-discovery-predictions.jsonl");const exactObservations=options.marketObservations || (options.snapshots?[]:loadExactMarketObservations());const snapshots=options.snapshots || (exactObservations.length?exactObservations:loadOutcomeSnapshots());const resolved=linkShadowPredictionsToOutcomes(predictions,snapshots,{asOf:now,horizonHours:24,maxLatenessHours:8,targetReturnPct:25,failureReturnPct:-20});writeAtomicJson("reports/market-discovery-resolved.json",{schemaVersion:1,generatedAt:now,predictions:predictions.length,resolved:resolved.length,rows:resolved.slice(-10000)});const leadRows=buildLeadTimes(predictions,snapshots,25,{asOf:now});const lead=evaluateLeadTimeModel(leadRows,{minimumSamples:50,targetLeadHours:12});writeAtomicJson("reports/market-discovery-lead-time.json",{...lead,generatedAt:now,rows:leadRows.slice(-5000)});const history=readJson("data/alpha-os-candidate-history.json",[])||[];const winner=resolved.filter(r=>Number(r.realizedReturnPct)>=50).sort((a,b)=>Number(b.realizedReturnPct)-Number(a.realizedReturnPct))[0];let earliest={state:"NO_MATURE_WINNER",candidates:[]};if(winner){const key=strictIdentityKey(winner);const winnerTimeline=history.filter(r=>strictIdentityKey(r)===key);const controls=[...new Set(history.map(strictIdentityKey).filter(k=>k!==key))].slice(0,10).map(k=>history.filter(r=>strictIdentityKey(r)===k));const breakoutAt=winner.outcomeObservedAt||winner.generatedAt;earliest=detectEarliestSeparatingCause(winnerTimeline,controls,{breakoutAt,minimumControls:3});}writeAtomicJson("reports/earliest-cause-analysis.json",{generatedAt:now,winnerIdentityKey:winner?strictIdentityKey(winner):null,...earliest});const accounting=accountEvidenceValue(readJsonl("data/research-value-accounting.jsonl"),{now});writeAtomicJson("reports/evidence-value-accounting.json",accounting);return{resolved,lead,earliest,accounting};}
if(import.meta.url===`file://${process.argv[1]}`){try{const r=runMarketDiscoveryLearningCycle();console.log(JSON.stringify({resolved:r.resolved.length,leadTimeState:r.lead.state,leadTimeScore:r.lead.alphaLeadTimeScore,earliestCause:r.earliest.state,researchSources:r.accounting.sources.length},null,2));}catch(error){console.error(error);process.exitCode=1;}}
