import fs from "fs";
import path from "path";
import "./config/loadEnv.js";
import { getFallbackResearchSeedCandidates } from "./data/fallbackResearchSeedConnector.js";
import { runIntelligencePipeline, summarizePipelineResults } from "./intelligencePipeline.js";
import { generateReports } from "./reports/reportOrchestrator.js";
import { publishGithubPagesDashboard } from "./reports/githubPagesPublisher.js";

const EXAMPLE_FILES = [
  "report.html",
  "report.json",
  "opportunities.csv",
  "state-of-art-signals.json",
  "ai-council.json",
  "research-os.json",
  "alpha-lab.json",
  "simulation-brain.json",
  "outcome-judge.json",
  "catalyst-radar.json",
  "dossier-swarm.json",
  "ai-command-center.json",
  "ai-research-commander.json",
  "alpha-investigator.json",
  "portfolio-war-room.json",
  "strategy-lab.json",
  "causal-alpha-brain.json",
  "autonomous-alpha-os.json",
  "alpha-dashboard-v2.json",
  "paper-trading-lab.json",
  "weight-optimizer.json",
  "breakout-brain.json",
  "high-tech-alpha-stack.json",
  "self-evolving-alpha-os.json",
  "alpha-theses.json",
  "alpha-contracts.json",
  "alpha-contract-leaderboard.json",
  "alpha-contract-receipts.json",
  "source-truth.json",
  "github-intelligence-pro.json",
  "roadmap.json",
  "source-router.json",
  "engine-audit.json",
  "summary.txt",
];

function copyExamples() {
  const examplesDir = path.resolve("examples");
  fs.mkdirSync(examplesDir, { recursive: true });

  const copied = [];

  for (const fileName of EXAMPLE_FILES) {
    const source = path.resolve("reports", fileName);
    const target = path.join(examplesDir, fileName);

    if (!fs.existsSync(source)) continue;

    fs.copyFileSync(source, target);
    copied.push(fileName);
  }

  const readme = `# Example Reports

These files are generated by \`npm run demo\` from built-in research seed projects.

They let GitHub visitors inspect the AI Council, AI Command Center, Research Commander, Alpha Investigator, Portfolio War Room, Autonomous Strategy Lab, Causal Alpha Brain, Autonomous Alpha OS, Alpha Dashboard v2, Paper Trading Lab, Weight Optimizer, Breakout Brain, High-Tech Alpha Stack, Proof-Carrying Alpha Contracts, Source Truth, GitHub Pro, Quantum Brain, Research OS, Simulation Brain, Outcome Judge, Catalyst Radar, Dossier Swarm, Source Router, Alpha Lab, roadmap, CSV export, and HTML dashboard without connecting API keys.

Open \`report.html\` locally, or inspect the JSON files directly.
`;

  fs.writeFileSync(path.join(examplesDir, "README.md"), readme);

  return copied;
}

async function main() {
  const startedAt = new Date();
  const limit = Number(process.env.DEMO_PROJECT_LIMIT || 8);
  const projects = getFallbackResearchSeedCandidates({ limit });

  process.env.WEB_RESEARCH_AGENT_LIMIT = process.env.WEB_RESEARCH_AGENT_LIMIT || "0";
  process.env.INTERNET_RESEARCH_PROJECT_LIMIT = process.env.INTERNET_RESEARCH_PROJECT_LIMIT || "0";
  process.env.X_PROJECT_LIMIT = process.env.X_PROJECT_LIMIT || "0";
  process.env.NEWS_PROJECT_LIMIT = process.env.NEWS_PROJECT_LIMIT || "0";

  console.log("Crypto Launch Intelligence demo");
  console.log(`Scanning ${projects.length} built-in sample projects...`);

  const results = await runIntelligencePipeline(projects, {
    saveMemory: false,
    webResearchAgent: { limit: 0 },
    externalIntelligence: {
      x: { limit: 0 },
      news: { limit: 0 },
      internet: { enabled: false, limit: 0 },
    },
    outcomeJudge: {
      snapshots: [],
      memory: [],
    },
    dossierSwarm: {
      limit: Number(process.env.DEMO_DOSSIER_SWARM_LIMIT || 8),
    },
  });
  const summary = summarizePipelineResults(results);
  const reportPaths = generateReports(results, {
    mode: "demo",
    startedAt: startedAt.toISOString(),
    completedAt: new Date().toISOString(),
    scannedProjects: results.length,
    note: "Generated from built-in research seed projects. No API keys required.",
  });
  const dashboard = publishGithubPagesDashboard();
  const examples = copyExamples();

  console.log("");
  console.log("Demo complete.");
  console.log(`Projects scanned: ${summary.scannedProjects}`);
  console.log(`AI strong-buy candidates: ${summary.aiStrongBuyCount}`);
  console.log(`Breakout Brain picks: ${summary.breakoutBrainSelectionCount}`);
  console.log(`High-tech alpha candidates: ${summary.highTechAlphaCandidateCount}`);
  console.log(`Self-evolving alpha candidates: ${summary.selfEvolvingAlphaCandidateCount}`);
  console.log(`Proof-carrying alpha candidates: ${summary.proofCarryingAlphaCandidateCount}`);
  console.log(`Accountable contract research: ${summary.accountablePriorityContractCount}`);
  console.log(`Pre-strong-buy setups: ${summary.preStrongBuyCount}`);
  console.log(`High AI disagreement: ${summary.highDisagreementCount}`);
  console.log(`HTML dashboard: ${reportPaths.htmlPath}`);
  console.log(`GitHub Pages preview: ${dashboard.urlPath}`);
  console.log(`Example files copied: ${examples.join(", ")}`);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main()
    .then(() => process.exit(0))
    .catch((error) => {
      console.error(error);
      process.exit(1);
    });
}

export { main };
